DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@START VARCHAR(50) = @START;
DECLARE @@DISPLAY VARCHAR(50) = @DISPLAY;


SET @@QUERY = '';
SET @@QUERY = 'SELECT * FROM ( SELECT ROW_NUMBER() OVER (ORDER BY ID ASC) ROW_NUM,
		ID
      ,[WP_PROJECT_ID]
      ,[JOB_NAME]
      ,[WP_IMPB_NO]
      ,[PROJECT_CODE]
      ,[PROJECT_NAME]
      ,[ID_TB_M_AREA]
      ,[AREA_NAME]
      ,[ID_TB_M_LOCATION]
      ,[LOC_NAME]
      ,[DEP_OR_DIV_CODE]
      ,[IMPLEMENT_DATE_FROM]
      ,[IMPLEMENT_DATE_TO]
      ,[EXECUTOR]
      ,[EXECUTOR_DESC]
      ,[ID_TB_M_COMPANY]
      ,[COMPANY_NAME]
      ,[EMPLOYEE_LEAD_PROJECT]
      ,[LEADER_NAME]
      ,[EMPLOYEE_SUPERVISOR_PROJECT]
      ,[SUPERVISOR_NAME]
      ,[CREATED_BY]
      ,[CREATED_DT]
      ,[CHANGED_BY]
      ,[CHANGED_DT]
      ,[IMAGE_PATH]
      ,[STATUS]
      ,[EVALUATION_NOTES]
      ,RATING_CONTRACTOR
	  ,SUPPORT_DOC
	  ,SUPPORT_PHOTO
    FROM dbo.VW_PROJECT_EXECUTION
    WHERE 1=1  
';

IF(@PROJECT_NAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND PROJECT_NAME LIKE ''%'+@PROJECT_NAME+'%'' ';
	END

IF(@PROJECT_LOCATION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TB_M_LOCATION = '''+@PROJECT_LOCATION+''' ';
	END

IF(@PROJECT_DATE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IMPLEMENT_DATE_FROM >= '''+@PROJECT_DATE+''' ';
	END

IF(@PROJECT_DATETO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IMPLEMENT_DATE_TO <= '''+@PROJECT_DATETO+''' ';
	END

IF(@DIVISION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND DEP_OR_DIV_CODE = '''+@DIVISION+''' ';
	END

IF(@COMPANY <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TB_M_COMPANY = '''+@COMPANY+''' ';
	END

IF(@PROJECT_CODE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND PROJECT_CODE LIKE ''%'+@PROJECT_CODE+'%'' ';
	END



IF(@WP_IMPB_NO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND WP_IMPB_NO = '''+@WP_IMPB_NO+''' ';
	END

SET @@QUERY = @@QUERY +') as TB';

IF(@@START > 0 AND @@DISPLAY > 0)
BEGIN	
	SET @@QUERY = @@QUERY +' WHERE ROW_NUM BETWEEN '+@@START+' AND '''+@@DISPLAY+''' ';
END

EXEC(@@QUERY)