SELECT COUNT(1) FROM TB_M_EMPLOYEE AS A 
INNER JOIN TB_R_WP_SECURITY_CHECK AS B ON A.ID_TB_M_EMPLOYEE = B.ID_TB_M_EMPLOYEE
INNER JOIN TB_R_WP_PROJECT_JOB AS C ON B.ID_TB_R_WP_PROJECT_JOB_ID = C.ID
WHERE C.WP_IMPB_NO = @IMPB_NO AND A.ID_TB_M_EMPLOYEE = @ID
AND CONVERT(DATE, B.DATE) = CONVERT(DATE, GETDATE())