DECLARE @@GETWHERE VARCHAR(MAX);
DECLARE @@QUERY VARCHAR(MAX);
IF(@TYPE  = 'IMPB')
BEGIN
	SET @@GETWHERE = 'B.WP_IMPB_NO = '''+@ID+''' ';
END
ELSE
BEGIN
	SET @@GETWHERE = 'B.ID = '''+@ID+''' ';
END

SET @@QUERY = 'SELECT 
(CASE WHEN A.EXECUTOR = 2
	THEN 
		(SELECT COMPANY_NAME FROM TB_M_COMPANY WHERE ID_TB_M_COMPANY = A.ID_TB_M_COMPANY)
	ELSE 
		(SELECT COMPANY_NAME FROM TB_M_COMPANY WHERE ID_TB_M_COMPANY = A.ID_TB_M_COMPANY)
	END
)  AS SECTION_OR_DIV,
 (SELECT FIRST_NAME +'' ''+LAST_NAME FROM TB_M_EMPLOYEE WHERE ID_TB_M_EMPLOYEE = A.EMPLOYEE_LEAD_PROJECT) AS PIMPINAN_PELAKSANA,
 (SELECT FIRST_NAME +'' ''+LAST_NAME FROM TB_M_EMPLOYEE WHERE ID_TB_M_EMPLOYEE = A.EMPLOYEE_SUPERVISOR_PROJECT) AS PENGAWAS_PELAKSANA,
 (SELECT FIRST_NAME +'' ''+LAST_NAME FROM TB_M_EMPLOYEE WHERE ID_TB_M_EMPLOYEE = A.EXECUTOR) AS PELAKSANA_PROYEK
FROM TB_R_WP_DETAIL_IMPLEMENTOR AS A 
INNER JOIN TB_R_WP_PROJECT_JOB AS B ON A.WP_PROJECT_JOB_ID = B.ID
WHERE ' + @@GETWHERE;

EXEC(@@QUERY);