SELECT * FROM (SELECT 
 ROW_NUMBER() OVER (ORDER BY B.CHECK_IN ASC) ROW_NUM,
 COUNT(*) OVER() AS TOTAL_ROW_NUM,
(FIRST_NAME + ' ' + LAST_NAME) AS FULLNAME, 
(SELECT (COMPANY_NAME + ' ('+COMPANY_INITIAL+')') AS COMPANY_NAME FROM TB_M_COMPANY WHERE ID_TB_M_COMPANY = A.ID_TB_M_COMPANY) AS COMPANY,
(D.AREA_NAME + ' - ' + D.LOC_NAME) AS LOCATION,
CONVERT(VARCHAR, B.CHECK_IN, 13) AS CHECK_IN
FROM TB_M_EMPLOYEE AS A 
INNER JOIN TB_R_WP_SECURITY_CHECK AS B ON A.ID_TB_M_EMPLOYEE = B.ID_TB_M_EMPLOYEE 
INNER JOIN TB_R_WP_PROJECT_JOB AS E ON B.ID_TB_R_WP_PROJECT_JOB_ID = E.ID
INNER JOIN TB_R_WP_PROJECT AS C ON E.WP_PROJECT_ID = C.ID
INNER JOIN (SELECT ID_TB_M_LOCATION, AREA_NAME, LOC_NAME FROM TB_M_LOCATION INNER JOIN TB_M_AREA ON TB_M_LOCATION.ID_TB_M_AREA = TB_M_AREA.ID_TB_M_AREA) AS D ON C.ID_TB_M_LOCATION = D.ID_TB_M_LOCATION
WHERE (B.CHECK_OUT = '' OR B.CHECK_OUT IS NULL)
) AS TB
WHERE ROW_NUM BETWEEN @start AND @end
ORDER BY CHECK_IN ASC