DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@DATA_ID VARCHAR(MAX) = @DATA_ID;
DECLARE @@TIME_UNIT_CRITERIA VARCHAR(MAX) = @TIME_UNIT_CRITERIA;
DECLARE @@EXECUTION_TIME VARCHAR(MAX) = @EXECUTION_TIME;
DECLARE @@STATUS_ACTIVE VARCHAR(MAX) = @STATUS_ACTIVE;

SET @@QUERY = '';
SET @@QUERY = '
	SELECT ISNULL(max(ROW_NUM),0) FROM 
	(
		SELECT DISTINCT ROW_NUMBER() OVER (ORDER BY ID ASC) ROW_NUM,
       ID
       ,[WP_PROJECT_ID]
      ,[JOB_NAME]
      ,[WP_IMPB_NO]
      ,[PROJECT_CODE]
      ,[PROJECT_NAME]
      ,[ID_TB_M_AREA]
      ,[AREA_NAME]
      ,[ID_TB_M_LOCATION]
      ,[LOC_NAME]
      ,[DEP_OR_DIV_CODE]
      ,[IMPLEMENT_DATE_FROM]
      ,[IMPLEMENT_DATE_TO]
      ,[EXECUTOR]
      ,[EXECUTOR_DESC]
      ,[ID_TB_M_COMPANY]
      ,[COMPANY_NAME]
      ,[EMPLOYEE_LEAD_PROJECT]
      ,[LEADER_NAME]
      ,[EMPLOYEE_SUPERVISOR_PROJECT]
      ,[SUPERVISOR_NAME]
      ,[CREATED_BY]
      ,[CREATED_DT]
      ,[CHANGED_BY]
      ,[CHANGED_DT]
      ,[IMAGE_PATH]
      ,[STATUS]
      ,[EVALUATION_NOTES]
      ,[RATING_CONTRACTOR]
    FROM dbo.VW_PROJECT_EXECUTION
    WHERE 1=1  
';

IF(@PROJECT_NAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND PROJECT_NAME LIKE ''%'+@PROJECT_NAME+'%'' ';
	END

IF(@PROJECT_LOCATION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TB_M_LOCATION = '''+@PROJECT_LOCATION+''' ';
	END

IF(@PROJECT_DATE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IMPLEMENT_DATE_FROM >= '''+@PROJECT_DATE+''' ';
	END

IF(@PROJECT_DATETO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IMPLEMENT_DATE_TO <= '''+@PROJECT_DATETO+''' ';
	END

IF(@DIVISION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND DEP_OR_DIV_CODE = '''+@DIVISION+''' ';
	END

IF(@COMPANY <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TB_M_COMPANY = '''+@COMPANY+''' ';
	END

IF(@PROJECT_CODE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND PROJECT_CODE LIKE ''%'+@PROJECT_CODE+'%'' ';
	END

IF(@WP_IMPB_NO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND WP_IMPB_NO = '''+@WP_IMPB_NO+''' ';
	END

SET @@QUERY = @@QUERY +' ) as TB';
EXEC(@@QUERY);

