DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
BEGIN TRY
	UPDATE TB_M_USER_PLANT SET USERNAME = @USERNAME, PLANT_CD = @PLANT_CD, PLANT_NM = @PLANT_NM, COMPANY = @COMPANY, CHANGED_BY = @username, CHANGED_DT = GETDATE() WHERE USERNAME = @ID
	SET @@CHK = 'TRUE';
	SET @@ERR = 'Data Has Been Updated';
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR UPDATE TB_M_USER_PLANT:' +@USERNAME+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS