INSERT INTO TB_R_LEARN_EXAM_QUESTION
(
	ID_TB_R_LEARN_EXAM_SUBJECT
	,ID_TB_M_LEARN_QUESTION
	,IS_DELETED
	,CREATED_BY
	,CREATED_DT
	,UPDATED_BY
	,UPDATED_DT
)
VALUES
(
	@IDSUBJECT
	,@IDQUESTION
	,0
	,@USERNAME
	,GETDATE()
	,@USERNAME
	,GETDATE()
);

SELECT ID_TB_R_LEARN_EXAM_QUESTION AS ID,
	'Dummy' AS TITLE
FROM TB_R_LEARN_EXAM_QUESTION
WHERE ID_TB_R_LEARN_EXAM_SUBJECT = @IDSUBJECT
	AND ID_TB_M_LEARN_QUESTION = @IDQUESTION