DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
BEGIN TRY
	UPDATE TB_R_WP_HEADER SET PROJECT_CODE = @PROJECT_CODE, PROJECT_NAME = @PROJECT_NAME, ID_TB_M_LOC = @LOCATION, IMPLEMENTATION_DATE = @DATE, IMPLEMENTATION_TIME = @TIME
,DIVISION = @DIVISION, EXECUTOR = @EXECUTOR, CONTRACTOR = @CONTRACTOR, LEADER = @LEADER, SUPERVISOR = @SUPERVISOR, STATUS = @STATUS, CHANGED_BY = @USERNAME, CHANGED_DT = GETDATE() WHERE ID = @ID
	SET @@CHK = 'TRUE';
	SET @@ERR = 'Data Has Been Updated';
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR UPDATE WP_HEADER:' +@PROJECT_CODE+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS