DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@START VARCHAR(50) = @START;
DECLARE @@DISPLAY VARCHAR(50) = @DISPLAY;


SET @@QUERY = '';
SET @@QUERY = 'SELECT * FROM ( SELECT ROW_NUMBER() OVER (ORDER BY NO ASC) ROW_NUM,
	   ID_TRANS as ID,
       ID_TRANS as ID_BUNDLE,
       DMC_CODE,
	   QTY_STD as QTY_BUNDLE_STD,
	   QTY as QTY_BUNDLE_ACT,
	   BERAT_STD as BERAT_BUNDLE_STD,
	   BERAT_ACT as BERAT_BUNDLE_ACT,
	   JENIS_LOTTO,
	   STATUS_LOTTO,
	   NIK_GAIKAN,
	   OPR_GAIKAN,
	   KETERANGAN,
	   SHF as SHIFT,
	   KALI_PRINT as JML_PRINT,
	   TRANS_DATE,
	   STATUS_CHECKER,
	   CHECKER,
	   CHECKER_DATE,
	   INPUT_ADM,
	   INPUT_DATE,
	   UPDATE_ADM,
	   UPDATE_DATE
    FROM dbo.Z_REX_Data_InOut_FG_New
    WHERE 1=1 and id_trans like ''B%''';

IF(@ID_BUNDLE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TRANS LIKE ''%'+@ID_BUNDLE+'%'' ';
	END
IF(@DMC_CODE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND DMC_CODE LIKE ''%'+@DMC_CODE+'%'' ';
	END
IF(@TRANS_DATE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND TRANS_DATE >= '''+@TRANS_DATE+''' ';
	END

IF(@TRANS_DATETO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND TRANS_DATE <= '''+@TRANS_DATETO+''' ';
	END

SET @@QUERY = @@QUERY +') as TB';

IF(@@START > 0 AND @@DISPLAY > 0)
BEGIN	
	SET @@QUERY = @@QUERY +' WHERE ROW_NUM BETWEEN '+@@START+' AND '''+@@DISPLAY+''' ';
END

EXEC(@@QUERY)