SELECT 
	ID_TB_R_LEARN_EXAM_SUBJECT AS ID
	,TITLE
	,PASSING_SCORE_REQUIREMENT
	,EXAM_DURATION
	,convert(varchar(10), DATE_EXAM_PERIOD_START, 120) AS DATE_START
	,convert(varchar(10), DATE_EXAM_PERIOD_END, 120) AS DATE_END
	,REMEDIAL
	,EXAM_TYPE
	,TOTAL_PUBLISHED
	,IS_PUBLISHED
FROM 
	TB_R_LEARN_EXAM_SUBJECT
WHERE
	ID_TB_R_LEARN_EXAM_SUBJECT = @ID 
