DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);

BEGIN TRY
	SET @@CNT = (SELECT COUNT(1) FROM TB_R_LEARN_EXAM_SUBJECT WHERE CONVERT(VARCHAR, TITLE) = @TITLE);
	IF(@@CNT > 0)
	BEGIN
		SELECT 
			@@MSG_TEXT = MSG_TEXT,
			@@MSG_TYPE = MSG_TYPE
		FROM dbo.FN_GENERATE_MSG('MPISSTD049E', 'EXAM SUBJECT : ' + @TITLE , NULL, NULL, NULL);
		SET @@CHK = 'FALSE';
		SET @@ERR = @@MSG_TEXT;

		
	END ELSE
	BEGIN
		
		INSERT INTO TB_R_LEARN_EXAM_SUBJECT
		(
			   [TITLE]
			  ,[PASSING_SCORE_REQUIREMENT]
			  ,[EXAM_DURATION]
			  ,[DATE_EXAM_PERIOD_START]
			  ,[DATE_EXAM_PERIOD_END]
			  ,[REMEDIAL]
			  ,[EXAM_TYPE]
			  ,[TOTAL_PUBLISHED]
			  ,[IS_PUBLISHED]
			  ,[EXAM_FOR]
			  ,[CREATED_BY]
			  ,[CREATED_DT]
			  ,[UPDATED_BY]
			  ,[UPDATED_DT]

		)
		VALUES
		(
			@TITLE
			,@PASSING_SCORE_REQUIREMENT
			,@EXAM_DURATION
			,@DATE_EXAM_PERIOD_START
			,@DATE_EXAM_PERIOD_END
			,@REMEDIAL
			,@EXAM_TYPE
			,@TOTAL_PUBLISHED
			,@IS_PUBLISHED
			,@Exam_For
			,@USERNAME
			,GETDATE()
			,@USERNAME
			,GETDATE()
		);


		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';
	END
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR EXAM SUBJECT :' +@TITLE+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS
