DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@DATA_ID VARCHAR(MAX) = @DATA_ID;
DECLARE @@TIME_UNIT_CRITERIA VARCHAR(MAX) = @TIME_UNIT_CRITERIA;
DECLARE @@EXECUTION_TIME VARCHAR(MAX) = @EXECUTION_TIME;
DECLARE @@STATUS_ACTIVE VARCHAR(MAX) = @STATUS_ACTIVE;

SET @@QUERY = '';
SET @@QUERY = '
	SELECT ISNULL(max(ROW_NUM),0) FROM 
	(
		SELECT ROW_NUMBER() OVER (ORDER BY A.ID_TB_M_WORKING_TYPE ASC) ROW_NUM,
		A.ID_TB_M_WORKING_TYPE,
		A.WORKING_NAME,
		A.STATUS,
		A.CREATE_BY,
		A.CREATE_DT,
		A.UPDATE_BY,
		A.UPDATE_DT
		FROM TB_M_WORKING_TYPE AS A
		WHERE 1=1 AND A.IS_DELETED = 0
';

IF(@WORKING_NAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.WORKING_NAME LIKE ''%'+RTRIM(@WORKING_NAME)+'%'' ';
	END
SET @@QUERY = @@QUERY +') as TB';


EXEC(@@QUERY);

