SELECT TOP 1 A.ID,A.PROJECT_CODE,A.PROJECT_NAME , 
B.AREA_NAME,
B.IMAGE_PATH AS AREA_PATH,
G.LOC_NAME AS LOCATION_NAME,
A.IMPLEMENT_DATE_FROM, A.IMPLEMENT_DATE_TO ,
D.ID_TB_M_COMPANY , F.COMPANY_NAME,
C.ID AS PROJECT_JOB_ID,
C.START_DATE,
C.END_DATE,
(C.JOB_NAME + ' '+C.WP_IMPB_NO) AS PROJECT_JOB,
(SELECT TOP 1 TITLE FROM TB_R_WP_DAILY WHERE TB_R_WP_PROJECT_JOB_ID = C.ID) AS TITLE
FROM TB_R_WP_PROJECT A
INNER JOIN TB_M_AREA B ON A.ID_TB_M_AREA = B.ID_TB_M_AREA
INNER JOIN TB_M_LOCATION G ON G.ID_TB_M_AREA = B.ID_TB_M_AREA
INNER JOIN TB_R_WP_PROJECT_JOB C ON C.WP_PROJECT_ID = A.ID
INNER JOIN TB_R_WP_DETAIL_IMPLEMENTOR D ON D.WP_PROJECT_JOB_ID = C.ID
INNER JOIN TB_M_COMPANY F ON D.ID_TB_M_COMPANY = F.ID_TB_M_COMPANY 
WHERE A.ID = @ID;
