DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX)
	, @@MSG VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);
DECLARE @@CHK_DELETE VARCHAR(5);
DECLARE @@COUNTER INT;
DECLARE @@MSG_START VARCHAR(MAX);
DECLARE @@MSG_SUCCESS VARCHAR(MAX);
DECLARE @@MSG_END VARCHAR(MAX);

BEGIN TRY
	SET @@CNT = (SELECT COUNT(1) FROM TB_R_WP_PROJECT_JOB WHERE ID = @ID);
	IF(@@CNT > 0)
	BEGIN
		SET @@COUNTER = (SELECT (CASE WHEN (SELECT COUNT(PROCESS_ID) FROM TB_R_LOG_H) = 0 THEN 1 ELSE (SELECT TOP 1 PROCESS_ID FROM TB_R_LOG_H ORDER BY PROCESS_ID DESC) + 1 END));
		EXEC SP_INSERT_UPDATE_LOG_H @username,'','WP02002',1,'1','Update',@@COUNTER;

		SET @@MSG_START = 'LOG001 : '+ (SELECT dbo.GenerateMessage('LOG001','','',''));
		EXEC SP_INSERT_LOG_D @@COUNTER, 'Start', 'LOG001', 'Info',  @@MSG_START;
		
		UPDATE TB_R_WP_PROJECT_JOB
		SET JOB_NAME = @JOB_NAME,
			JOB_STATUS = @JOB_STATUS,
			WP_IMPB_NO = @WP_IMPB_NO,
			RISK_LEVEL = @RISK_LEVEL,
			[CHANGED_BY] = @username,
			[CHANGED_DT] = GETDATE()
		WHERE ID = @ID

		IF(@JOB_STATUS = 'SUBMITED')
		BEGIN
			EXEC [RUMAHITBDG_SQL2017].[AB070_DB].[dbo].[SP_SEND_MAIL] @ID;
		END

		SET @@MSG_SUCCESS  = 'MWP003 : '+ (SELECT dbo.GenerateMessage('MWP003','IMPB DATA','',''));
		EXEC SP_INSERT_LOG_D @@COUNTER, 'Updated', 'MWP003', 'Info',  @@MSG_SUCCESS;

		SET @@MSG_END  = 'LOG007 : '+ (SELECT dbo.GenerateMessage('LOG007','','',''));
		EXEC SP_INSERT_LOG_D @@COUNTER, 'END', 'LOG007', 'Info',  @@MSG_END;

		EXEC SP_INSERT_UPDATE_LOG_H 
		@username,'','WP02002','1',1,'Update',@@COUNTER;
		
		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';
	END ELSE
	BEGIN
		INSERT INTO TB_R_WP_PROJECT_JOB
		(
			WP_PROJECT_ID ,
			JOB_NAME ,
			JOB_STATUS,
			WP_IMPB_NO ,
			RISK_LEVEL,
			CREATED_BY ,
			CREATED_DT ,
			CHANGED_BY ,
			CHANGED_DT 
			
		)
		VALUES
		(
			@WP_PROJECT_ID,
			@JOB_NAME,
			@JOB_STATUS,
			@WP_IMPB_NO,
			@RISK_LEVEL,
			@username,
			GETDATE(),
			@username,
			GETDATE()
		);

		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';
	END
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR UPDATE WP_PROJECT_JOB:' +@JOB_NAME+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS,CAST(@@CNT AS VARCHAR(20)) AS WP_PROJECT_JOB_ID