DECLARE @@CHK INT;

SET @@CHK = (SELECT COUNT(1) FROM TB_R_IMPB_LOCATION WHERE ID_TB_R_WP_PROJECT_JOB = @WP_PROJECT_JOB_ID);

IF(@@CHK < 1)
BEGIN
		INSERT INTO TB_R_IMPB_LOCATION 
		(
			[ID_TB_R_WP_PROJECT_JOB],
			[TOP_POSITION],
			[LEFT_POSITION],
			[HEIGHT],
			[WIDTH],
			[PING],
			[WINDOW_HEIGHT],
			[WINDOW_WIDTH],
			[BORDER_COLOR],
			[ROTATION]
		)
		
		VALUES(
			@WP_PROJECT_JOB_ID,
			@TOP_POS,
			@LEFT_POS,
			@HEIGHT_SQUARE,
			@WIDTH_SQUARE,
			0,
			@WINDOW_HEIGHT,
			@WINDOW_WIDTH,
			@BORDER_COLOR,
			@ROTATE
		);
END
ELSE
BEGIN
	UPDATE TB_R_IMPB_LOCATION SET
		TOP_POSITION = @TOP_POS,
		LEFT_POSITION = @LEFT_POS,
		HEIGHT = @HEIGHT_SQUARE,
		WIDTH = @WIDTH_SQUARE,
		PING = 0,
		WINDOW_HEIGHT = @WINDOW_HEIGHT,
		WINDOW_WIDTH = @WINDOW_WIDTH,
		ROTATION = @ROTATE
	WHERE ID_TB_R_WP_PROJECT_JOB = @WP_PROJECT_JOB_ID
END