SELECT [TB_R_WP_DAILY_ID]
      ,w.[TB_M_EMPLOYEE_ID]
      ,w.[ACTIVE]
	  ,a.TB_R_WP_PROJECT_JOB_ID
	  ,e.FIRST_NAME + ' ' + e.LAST_NAME as NAME,
	  e.ID_TB_M_EMPLOYEE, 
	  e.ID_TB_M_COMPANY, 
	  e.PHONE, 
	  e.PIC_STATUS, 
	  e.ANZEN_SERTIFICATE_NO 
FROM [AB070_DB].[dbo].[TB_R_WP_DAILY_WORKER_LIST] w
INNER JOIN [AB070_DB].[dbo].[TB_R_WP_DAILY] a on w.TB_R_WP_DAILY_ID = a.ID
INNER JOIN TB_M_EMPLOYEE e on e.ID_TB_M_EMPLOYEE = w.[TB_M_EMPLOYEE_ID]
where a.STATUS = 'SUBMITED'
AND w.[ACTIVE] = 1
AND a.TB_R_WP_PROJECT_JOB_ID = @WP_PROJECT_JOB_ID