SELECT DISTINCT TR.[TRAINING_SCH_ID]
	,HR.DIVISION
	,HR.DEPARTEMENT
	FROM [dbo].[TB_R_TRAINING_H] TR
	JOIN [dbo].[HRWEB] HR ON TR.[NOREG] = HR.[NOREG]
	JOIN [dbo].[TB_M_TRAINING_SCHED_H] TH ON TR.[TRAINING_SCH_ID] = TH.[TRAINING_SCH_ID]
	WHERE TR.[TRAINING_SCH_ID] = @TRAINING_SCH_ID AND TR.[PAX_STS] = '6'