DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@DATA_ID VARCHAR(MAX) = @DATA_ID;
DECLARE @@TIME_UNIT_CRITERIA VARCHAR(MAX) = @TIME_UNIT_CRITERIA;
DECLARE @@EXECUTION_TIME VARCHAR(MAX) = @EXECUTION_TIME;
DECLARE @@STATUS_ACTIVE VARCHAR(MAX) = @STATUS_ACTIVE;

SET @@QUERY = '';
SET @@QUERY = '
	SELECT ISNULL(max(ROW_NUM),0) FROM 
	(
		SELECT ROW_NUMBER() OVER (ORDER BY a.ID ASC) ROW_NUM,
	ID, Project_CD, Project_Name, Location, convert(varchar(10),Tanggal_Pelaksanaan) as Tanggal_Pelaksanaan, convert(varchar(25), Jam_Pelaksanaan, 120) AS Jam_Pelaksanaan, Divisi_Dept AS DIVISION, SYSTEM_VALUE_TXT AS Status, Pelaksana, Nama_Kontraktor,
	Nama_Pimpinan AS NAMA_PIMPINAN, Nama_Pengawas, CREATE_BY, CREATE_DT, UPDATE_BY AS CHANGED_BY, UPDATE_DT AS CHANGED_DT
	FROM dbo.TB_R_WP_HEADER as a  LEFT JOIN (SELECT SYSTEM_CD, SYSTEM_VALUE_TXT FROM TB_M_SYSTEM WHERE SYSTEM_ID = ''WP_STATUS'') AS b ON a.Status = b.SYSTEM_CD
	) AS TB';

EXEC(@@QUERY);

