DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);

DECLARE @@STATUS INT = 0;
DECLARE @@COUNTER INT= (SELECT (CASE WHEN (SELECT COUNT(PROCESS_ID) FROM TB_R_LOG_H) = 0 THEN 1 ELSE (SELECT TOP 1 PROCESS_ID FROM TB_R_LOG_H ORDER BY PROCESS_ID DESC) + 1 END));
EXEC SP_INSERT_UPDATE_LOG_H @USERNAME,'','WP01004',1,'1','Update',@@COUNTER;

DECLARE @@MSG_START VARCHAR(MAX) = 'LOG001 : '+ (SELECT dbo.GenerateMessage('LOG001','','',''));
EXEC SP_INSERT_LOG_D @@COUNTER, 'Start', 'LOG001', 'Info',  @@MSG_START;

IF(@STATUS = 'null')
BEGIN
	SET @@STATUS = 0;
END
ELSE
BEGIN
	SET @@STATUS = @STATUS;
END
DECLARE @@MSG_CHECK VARCHAR(MAX) = 'LOG002 : '+ (SELECT dbo.GenerateMessage('LOG002','','',''));
EXEC SP_INSERT_LOG_D @@COUNTER, 'Check', 'LOG002', 'Info',  @@MSG_CHECK;

BEGIN TRY
	UPDATE TB_M_WORKING_TYPE SET WORKING_NAME = @WORKING_NAME, STATUS = @STATUS, ICON=@ICON, UPDATE_BY = @USERNAME, UPDATE_DT = GETDATE() WHERE ID_TB_M_WORKING_TYPE = @ID
	SET @@CHK = 'TRUE';
	SET @@ERR = 'Data Has Been Updated';
	DECLARE @@MSG_SUCCESS VARCHAR(MAX) = 'MWP003 : '+ (SELECT dbo.GenerateMessage('MWP003','WORKING TYPE','',''));
	EXEC SP_INSERT_LOG_D @@COUNTER, 'Updated', 'MWP003', 'Info',  @@MSG_SUCCESS;
END TRY
BEGIN CATCH
	DECLARE @@MSG_ERROR VARCHAR(MAX) = ERROR_MESSAGE();
	EXEC SP_INSERT_LOG_D @@COUNTER, 'ERROR', 'Error', 'ERROR',  @@MSG_ERROR;

	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR UPDATE TB_M_WORKING_TYPE : ' +@WORKING_NAME+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS

DECLARE @@MSG_END VARCHAR(MAX) = 'LOG007 : '+ (SELECT dbo.GenerateMessage('LOG007','','',''));
EXEC SP_INSERT_LOG_D @@COUNTER, 'END', 'LOG007', 'Info',  @@MSG_END;

EXEC SP_INSERT_UPDATE_LOG_H 
@USERNAME,'','WP01004','1',1,'CREATE',@@COUNTER;