 DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);
DECLARE @@CHK_DELETE VARCHAR(5);

DECLARE @@COUNTER INT= (SELECT (CASE WHEN (SELECT COUNT(PROCESS_ID) FROM TB_R_LOG_H) = 0 THEN 1 ELSE (SELECT TOP 1 PROCESS_ID FROM TB_R_LOG_H ORDER BY PROCESS_ID DESC) + 1 END));
EXEC SP_INSERT_UPDATE_LOG_H @USERNAME,'','WP01004',1,'1','CREATE',@@COUNTER;

DECLARE @@MSG_START VARCHAR(MAX) = 'LOG001 : '+ (SELECT dbo.GenerateMessage('LOG001','','',''));
EXEC SP_INSERT_LOG_D @@COUNTER, 'Start', 'LOG001', 'Info',  @@MSG_START;

BEGIN TRY
	SET @@CNT = (SELECT COUNT(1) FROM TB_M_WORKING_TYPE WHERE WORKING_NAME = @WORKING_NAME);
	SET @@CHK_DELETE = (SELECT TOP 1 IS_DELETED FROM TB_M_WORKING_TYPE WHERE WORKING_NAME = @WORKING_NAME);

	DECLARE @@MSG_CHECK VARCHAR(MAX) = 'LOG002 : '+ (SELECT dbo.GenerateMessage('LOG002','','',''));
	EXEC SP_INSERT_LOG_D @@COUNTER, 'Check', 'LOG002', 'Info',  @@MSG_CHECK;

	IF(@@CNT > 0)
	BEGIN
		


		SET @@CHK = 'FALSE';
		SET @@ERR = 'DUPLICATE';

		DECLARE @@MSG_WARNING VARCHAR(MAX) = 'MWP004 : '+ (SELECT dbo.GenerateMessage('MWP004','WORKING TYPE','',''));
		EXEC SP_INSERT_LOG_D @@COUNTER, 'Duplicate', 'MWP004', 'Info',  @@MSG_WARNING;
		
	END ELSE
	BEGIN
		
		INSERT INTO TB_M_WORKING_TYPE
		(
			 [WORKING_NAME]
			,[STATUS]
			,[ICON]
			,[CREATE_BY]
			,[CREATE_DT]
			,[UPDATE_BY]
			,[UPDATE_DT]
			,[IS_DELETED]
			
		)
		VALUES
		(
			@WORKING_NAME,
			@STATUS,
			@ICON,
			@USERNAME,
			GETDATE(),
			@USERNAME,
			GETDATE(),
			0
		);

		DECLARE @@MSG_SUCCESS VARCHAR(MAX) = 'MWP001 : '+ (SELECT dbo.GenerateMessage('MWP001','WORKING TYPE MASTER','',''));
		EXEC SP_INSERT_LOG_D @@COUNTER, 'Duplicate', 'MWP001', 'Info',  @@MSG_SUCCESS;


		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';
	END
END TRY
BEGIN CATCH

DECLARE @@MSG_ERROR VARCHAR(MAX) = ERROR_MESSAGE();
	EXEC SP_INSERT_LOG_D @@COUNTER, 'ERROR', 'Error', 'ERROR',  @@MSG_ERROR;

	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR INSERT TB_M_WORKING_TYPE:' +@WORKING_NAME+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS

DECLARE @@MSG_END VARCHAR(MAX) = 'LOG007 : '+ (SELECT dbo.GenerateMessage('LOG007','','',''));
EXEC SP_INSERT_LOG_D @@COUNTER, 'END', 'LOG007', 'Info',  @@MSG_END;

EXEC SP_INSERT_UPDATE_LOG_H 
@USERNAME,'','WP01004','1',1,'CREATE',@@COUNTER;