--DECLARE @DMC_CODE VARCHAR(max) = 'TP-4750S1F0'
--=========================================================
--AKUMULASI PRICE MATERIAL COST DAN MATERIAL COST USAGE
--=========================================================


SELECT
	[ACC].DMC_CODE,
	MAX([TR].AIR_JPN) as AIR_JPN,
	MAX([TR].SEA_TOKYO) as SEA_TOKYO,
	MAX([TR].AIR_SHA) as AIR_SHA,
	MAX([TR].SEA_SHA) as SEA_SHA,
	MAX([TR].AIR_HKG) as AIR_HKG,
	MAX([TR].SEA_HKG) as SEA_HKG,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_F) AKUMULASI_PRICE_MATERIAL_PER_PCS_F,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_G) AKUMULASI_PRICE_MATERIAL_PER_PCS_G,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_T) AKUMULASI_PRICE_MATERIAL_PER_PCS_T,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_A) AKUMULASI_PRICE_MATERIAL_PER_PCS_A,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_P) AKUMULASI_PRICE_MATERIAL_PER_PCS_P,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_F) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_F,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_G) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_G,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_T) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_T,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_H) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_H,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_A) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_A,
	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_P) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_P,
	LABOR_COST_PRINTING_F,
	LABOR_COST_PRINTING_G, 
	LABOR_COST_PRINTING_T,
	LABOR_COST_NON_PRINTING_F,
	LABOR_COST_NON_PRINTING_G,
	LABOR_COST_NON_PRINTING_T,
	LABOR_COST_PRESS_F,
	LABOR_COST_PRESS_G,
	LABOR_COST_PRESS_T,
	LABOR_COST_ETCHING_F,
	LABOR_COST_ETCHING_G,
	TOTAL_LABOR_COST_CHUKAN_FILM,
	TOTAL_LABOR_COST_CHUKAN_GLASS,
	TOTAL_LABOR_COST_DENKI_TAIL,
	TOTAL_LABOR_COST_GAIKAN_TAIL,
	TOTAL_LABOR_COST_CEK_KELENGKAPAN_TAIL,
	TOTAL_LABOR_COST_TAIL_SASHI,
	TOTAL_LABOR_COST_HARIAWASE,
	TOTAL_LABOR_COST_OVEN,
	TOTAL_LABOR_COST_ANNEALING,
	TOTAL_LABOR_COST_HEATSEAL,
	TOTAL_LABOR_COST_HOKYOTAPE,
	TOTAL_LABOR_COST_FUREKENSA,
	TOTAL_LABOR_COST_DENKI,
	TOTAL_LABOR_COST_DOUBLE_TAPE,
	TOTAL_LABOR_COST_BARCODE_LABEL,
	TOTAL_LABOR_COST_GAIKAN_1X,
	TOTAL_LABOR_COST_GAIKAN_2X
FROM
	(
		SELECT 
			M.DMC_CODE,
			M.PART,
			M.DMC_CODE_PARTS,	
			CASE WHEN M.PART = 'F' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_F,
			CASE WHEN M.PART = 'G' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_G,
			CASE WHEN M.PART = 'T' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_T,
			CASE WHEN M.PART = 'A' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_A,
			CASE WHEN M.PART = 'P' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_P,
			CASE WHEN M.PART = 'F' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_F,
			CASE WHEN M.PART = 'G' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_G,
			CASE WHEN M.PART = 'T' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_T,
			0 as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_H,
			CASE WHEN M.PART = 'A' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_A,
			CASE WHEN M.PART = 'P' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_P					
		FROM 
			ad_dis_pc_production_cost_material M
		LEFT OUTER JOIN
			(SELECT 
				DMC_CODE, 
				DMC_CODE_PARTS,
				PART,						
				SUM(PRICE_PER_PCS) as PRICE_PER_PCS
			FROM
				ad_dis_pc_production_cost_material_usage
			WHERE 
				--SELAIN CHUKAN GLASS & FILM, DENKI, DENKI TAIL, GAIKAN, GAIKAN TAIL, CEK KELENGKAPAN 
				kode_proses not in (3030, 3040, 3120, 3140, 3155, 5190, 5220, 5230)
			GROUP BY
				DMC_CODE, 
				DMC_CODE_PARTS,
				PART				
				) as MU ON M.DMC_CODE = MU.DMC_CODE AND M.DMC_CODE_PARTS = MU.DMC_CODE_PARTS 
		GROUP BY
			M.DMC_CODE,
			M.PART,
			MU.pART,
			M.DMC_CODE_PARTS,
			MU.PRICE_PER_PCS

		--AMBIL DATA PART OTHERS 
		UNION 
			SELECT 
				DMC_CODE, 
				PART,
				DMC_CODE_PARTS,			
				0 as AKUMULASI_PRICE_MATERIAL_PER_PCS_F,
				0 as AKUMULASI_PRICE_MATERIAL_PER_PCS_G,
				0 as AKUMULASI_PRICE_MATERIAL_PER_PCS_T,
				0 as AKUMULASI_PRICE_MATERIAL_PER_PCS_A,
				0 as AKUMULASI_PRICE_MATERIAL_PER_PCS_P,
				0 as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_F,
				0 as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_G,
				0 as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_T,
				SUM(price_per_pcs) as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_H,
				0 as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_A,
				0 as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_P			
			FROM
				ad_dis_pc_production_cost_material_usage
			WHERE 
				PART like 'OTHERS'
			GROUP BY
				DMC_CODE, 
				DMC_CODE_PARTS,
				PART		
	) AS [ACC]

--====================================================
--JOIN DENGAN LABOR COST PRINTNG, NON PRINTING, PRESS
--====================================================

LEFT OUTER JOIN 
		(
			SELECT
				[LC].DMC_CODE,	
				--SUM([LC].PRICE_PER_PCS) AS PRICE_PER_PCS, 
				SUM([LC].PRINTING_F) AS LABOR_COST_PRINTING_F,
				SUM([LC].PRINTING_G) AS LABOR_COST_PRINTING_G,
				SUM([LC].PRINTING_T) AS LABOR_COST_PRINTING_T,
				SUM([LC].NON_PRINTING_F) AS LABOR_COST_NON_PRINTING_F,
				SUM([LC].NON_PRINTING_G) AS LABOR_COST_NON_PRINTING_G,
				SUM([LC].NON_PRINTING_T) AS LABOR_COST_NON_PRINTING_T,
				SUM([LC].PRESS_F) AS LABOR_COST_PRESS_F,
				SUM([LC].PRESS_G) AS LABOR_COST_PRESS_G,
				SUM([LC].PRESS_T) AS LABOR_COST_PRESS_T,
				SUM([LC].ETCHING_F) AS LABOR_COST_ETCHING_F,
				SUM([LC].ETCHING_G) AS LABOR_COST_ETCHING_G
			FROM(
					SELECT
						DMC_CODE,			
						CASE WHEN C.FACTORY = 'printing' and MU.PART = 'FILM' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRINTING_F,
						CASE WHEN C.FACTORY = 'printing' and MU.PART = 'GLASS' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRINTING_G,
						CASE WHEN C.FACTORY = 'printing' and MU.PART = 'TAIL' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRINTING_T,
						CASE WHEN C.FACTORY = 'non printing' and MU.PART = 'FILM' THEN SUM(PRICE_PER_PCS) ELSE 0 END as NON_PRINTING_F,
						CASE WHEN C.FACTORY = 'non printing' and MU.PART = 'GLASS' THEN SUM(PRICE_PER_PCS) ELSE 0 END as NON_PRINTING_G,
						CASE WHEN C.FACTORY = 'non printing' and MU.PART = 'TAIL' THEN SUM(PRICE_PER_PCS) ELSE 0 END as NON_PRINTING_T,
						CASE WHEN C.FACTORY = 'press' and MU.PART = 'FILM' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRESS_F,
						CASE WHEN C.FACTORY = 'press' and MU.PART = 'GLASS' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRESS_G,
						CASE WHEN C.FACTORY = 'press' and MU.PART = 'TAIL' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRESS_T,
						CASE WHEN C.FACTORY = 'etching' and MU.PART = 'FILM' THEN SUM(PRICE_PER_PCS) ELSE 0 END as ETCHING_F,
						CASE WHEN C.FACTORY = 'etching' and MU.PART = 'GLASS' THEN SUM(PRICE_PER_PCS) ELSE 0 END as ETCHING_G
					FROM
						ad_dis_pc_production_cost_material_usage MU
					INNER JOIN
						[ad_dis_pc_master_chinritsu] C ON MU.KODE_PROSES = C.ID_KOTEI AND SUBSTRING(MU.PART, 1, 1) = C.PART
					WHERE 
						--SELAIN CHUKAN GLASS & FILM, DENKI, DENKI TAIL, GAIKAN, GAIKAN TAIL, CEK KELENGKAPAN 
						kode_proses not in (3030, 3040, 3120, 3140, 3155, 5190, 5220, 5230)
					GROUP BY
					DMC_CODE,
					MU.PART,
					KODE_PROSES,
					C.FACTORY
			) AS [LC]
			--WHERE [LC].DMC_CODE = 'TP-4750S1F0'
			GROUP BY 
				[LC].DMC_CODE
		) AS [LC] 
ON [ACC].DMC_CODE = [LC] .DMC_CODE

--============================================================================
--JOIN DENGAN LABOR COST PROSES CHUK FILM, CHUK GLASS, DENKI TAIL, GAIKAN TAIL
--============================================================================

LEFT OUTER JOIN 
		(			
			SELECT
				[TLC].DMC_CODE,
				SUM([TLC].TOTAL_LABOR_COST_CHUKAN_FILM) as TOTAL_LABOR_COST_CHUKAN_FILM,
				SUM([TLC].TOTAL_LABOR_COST_CHUKAN_GLASS) as TOTAL_LABOR_COST_CHUKAN_GLASS,
				SUM([TLC].TOTAL_LABOR_COST_DENKI_TAIL) as TOTAL_LABOR_COST_DENKI_TAIL,
				SUM([TLC].TOTAL_LABOR_COST_GAIKAN_TAIL) as TOTAL_LABOR_COST_GAIKAN_TAIL,
				SUM([TLC].TOTAL_LABOR_COST_CEK_KELENGKAPAN_TAIL) as TOTAL_LABOR_COST_CEK_KELENGKAPAN_TAIL,
				SUM([TLC].TOTAL_LABOR_COST_TAIL_SASHI) as TOTAL_LABOR_COST_TAIL_SASHI,
				SUM([TLC].TOTAL_LABOR_COST_HARIAWASE) as TOTAL_LABOR_COST_HARIAWASE,
				SUM([TLC].TOTAL_LABOR_COST_OVEN) as TOTAL_LABOR_COST_OVEN,
				SUM([TLC].TOTAL_LABOR_COST_ANNEALING) as TOTAL_LABOR_COST_ANNEALING,
				SUM([TLC].TOTAL_LABOR_COST_HEATSEAL) as TOTAL_LABOR_COST_HEATSEAL,
				SUM([TLC].TOTAL_LABOR_COST_HOKYOTAPE) as TOTAL_LABOR_COST_HOKYOTAPE,
				SUM([TLC].TOTAL_LABOR_COST_FUREKENSA) as TOTAL_LABOR_COST_FUREKENSA,
				SUM([TLC].TOTAL_LABOR_COST_DENKI) as TOTAL_LABOR_COST_DENKI,
				SUM([TLC].TOTAL_LABOR_COST_DOUBLE_TAPE) as TOTAL_LABOR_COST_DOUBLE_TAPE,
				SUM([TLC].TOTAL_LABOR_COST_BARCODE_LABEL) as TOTAL_LABOR_COST_BARCODE_LABEL,
				SUM([TLC].TOTAL_LABOR_COST_GAIKAN_1X) as TOTAL_LABOR_COST_GAIKAN_1X,
				SUM([TLC].TOTAL_LABOR_COST_GAIKAN_2X) as TOTAL_LABOR_COST_GAIKAN_2X
			FROM 
					(
						SELECT 
							DMC_CODE,
							NAMA_PROSES,		
							CASE WHEN NAMA_PROSES like 'Chukan Film' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_CHUKAN_FILM,
							CASE WHEN NAMA_PROSES like 'Chukan Glass' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_CHUKAN_GLASS,
							CASE WHEN NAMA_PROSES like 'Denki Tail' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_DENKI_TAIL,							
							CASE WHEN NAMA_PROSES like 'Gaikan Tail' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_GAIKAN_TAIL,
							CASE WHEN NAMA_PROSES like 'Cek Kelengkapan Tail' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_CEK_KELENGKAPAN_TAIL,
							CASE WHEN NAMA_PROSES like 'Tail Sashi' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_TAIL_SASHI,
							CASE WHEN NAMA_PROSES like 'Hariawase' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_HARIAWASE,
							CASE WHEN NAMA_PROSES like 'Oven 120C 60Mnt' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_OVEN,
							CASE WHEN NAMA_PROSES like 'Annealing' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_ANNEALING,
							CASE WHEN NAMA_PROSES like 'FPC/Jogekan Heatseal' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_HEATSEAL,
							CASE WHEN NAMA_PROSES like 'Hokyotape Tail' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_HOKYOTAPE,
							CASE WHEN NAMA_PROSES like 'Fure kensa' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_FUREKENSA,
							CASE WHEN NAMA_PROSES like 'Denki 1x' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_DENKI,							
							CASE WHEN NAMA_PROSES like 'Double Tape' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_DOUBLE_TAPE,
							CASE WHEN NAMA_PROSES like 'Assy Barcode Label' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_BARCODE_LABEL,
							CASE WHEN NAMA_PROSES like 'Gaikan 1x' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_GAIKAN_1X,
							CASE WHEN NAMA_PROSES like 'Gaikan 2x' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_GAIKAN_2X
						FROM
							ad_dis_pc_production_cost_material_usage MU	
						GROUP BY 
							dmc_code,nama_proses
					) AS [TLC]	
					GROUP BY [TLC].DMC_CODE
			) AS [TLC]
ON [ACC].DMC_CODE = [TLC] .DMC_CODE

--============================================================================
--JOIN TRANSPORTATION COST
--============================================================================

LEFT OUTER JOIN 
		(
			SELECT
				item_code,
				SUM(AIR_JPN) as AIR_JPN,
				SUM(SEA_TOKYO) as SEA_TOKYO,
				SUM(AIR_SHA) as AIR_SHA,
				SUM(SEA_SHA) as SEA_SHA,
				SUM(AIR_HKG) as AIR_HKG,
				SUM(SEA_HKG) as SEA_HKG
			FROM
			(
				SELECT	
					item_code,
					case when TR.jenis_transportation LIKE '%Trans Cost Air JPN%' then TR.total_cost else 0 end as AIR_JPN,					
					case when TR.jenis_transportation LIKE '%Trans Cost Sea Tokyo%' then TR.total_cost else 0 end as SEA_TOKYO,
					case when TR.jenis_transportation LIKE '%Trans Cost Air Sha%' then TR.total_cost else 0 end as AIR_SHA,
					case when TR.jenis_transportation LIKE '%Trans Cost Sea Sha%' then TR.total_cost else 0 end as SEA_SHA,
					case when TR.jenis_transportation LIKE '%Trans Cost Air Hkg%' then TR.total_cost else 0 end as AIR_HKG,
					case when TR.jenis_transportation LIKE '%Trans Cost Sea Hkg%' then TR.total_cost else 0 end as SEA_HKG
				FROM
					ad_dis_pc_master_transportation TR
				WHERE 
					item_code = @DMC_CODE
			) as Trans
			GROUP BY item_code
		) AS [TR]
ON [ACC].DMC_CODE = [TR].item_code
--WHERE [ACC].DMC_CODE = 'TP-4750S1F0'
WHERE [ACC].DMC_CODE = @DMC_CODE

GROUP BY 
	[ACC].DMC_CODE, 	
	LABOR_COST_PRINTING_F,
	LABOR_COST_PRINTING_G, 
	LABOR_COST_PRINTING_T,
	LABOR_COST_NON_PRINTING_F,
	LABOR_COST_NON_PRINTING_G,
	LABOR_COST_NON_PRINTING_T,
	LABOR_COST_PRESS_F,
	LABOR_COST_PRESS_G,
	LABOR_COST_PRESS_T,
	LABOR_COST_ETCHING_F,
	LABOR_COST_ETCHING_G,
	TOTAL_LABOR_COST_CHUKAN_FILM,
	TOTAL_LABOR_COST_CHUKAN_GLASS,
	TOTAL_LABOR_COST_DENKI_TAIL,
	TOTAL_LABOR_COST_GAIKAN_TAIL,
	TOTAL_LABOR_COST_CEK_KELENGKAPAN_TAIL,
	TOTAL_LABOR_COST_TAIL_SASHI,
	TOTAL_LABOR_COST_HARIAWASE,
	TOTAL_LABOR_COST_OVEN,
	TOTAL_LABOR_COST_ANNEALING,
	TOTAL_LABOR_COST_HEATSEAL,
	TOTAL_LABOR_COST_HOKYOTAPE,
	TOTAL_LABOR_COST_FUREKENSA,
	TOTAL_LABOR_COST_DENKI,
	TOTAL_LABOR_COST_DOUBLE_TAPE,
	TOTAL_LABOR_COST_BARCODE_LABEL,
	TOTAL_LABOR_COST_GAIKAN_1X,
	TOTAL_LABOR_COST_GAIKAN_2X



----=========================================================
----AKUMULASI PRICE MATERIAL COST DAN MATERIAL COST USAGE
----=========================================================

--SELECT
--	[ACC].DMC_CODE,
--	MAX([TR].AIR_JPN) as AIR_JPN,
--	MAX([TR].SEA_TOKYO) as SEA_TOKYO,
--	MAX([TR].AIR_SHA) as AIR_SHA,
--	MAX([TR].SEA_SHA) as SEA_SHA,
--	MAX([TR].AIR_HKG) as AIR_HKG,
--	MAX([TR].SEA_HKG) as SEA_HKG,
--	MAX([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_F) AKUMULASI_PRICE_MATERIAL_PER_PCS_F,
--	MAX([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_G) AKUMULASI_PRICE_MATERIAL_PER_PCS_G,
--	MAX([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_T) AKUMULASI_PRICE_MATERIAL_PER_PCS_T,
--	MAX([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_A) AKUMULASI_PRICE_MATERIAL_PER_PCS_A,
--	MAX([ACC].AKUMULASI_PRICE_MATERIAL_PER_PCS_P) AKUMULASI_PRICE_MATERIAL_PER_PCS_P,
--	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_F) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_F,
--	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_G) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_G,
--	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_T) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_T,
--	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_A) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_A,
--	SUM([ACC].AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_P) AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_P,
--	LABOR_COST_PRINTING_F,
--	LABOR_COST_PRINTING_G, 
--	LABOR_COST_PRINTING_T,
--	LABOR_COST_NON_PRINTING_F,
--	LABOR_COST_NON_PRINTING_G,
--	LABOR_COST_NON_PRINTING_T,
--	LABOR_COST_PRESS_F,
--	LABOR_COST_PRESS_G,
--	LABOR_COST_PRESS_T,
--	LABOR_COST_ETCHING_F,
--	LABOR_COST_ETCHING_G,
--	TOTAL_LABOR_COST_CHUKAN_FILM,
--	TOTAL_LABOR_COST_CHUKAN_GLASS,
--	TOTAL_LABOR_COST_DENKI_TAIL,
--	TOTAL_LABOR_COST_GAIKAN_TAIL,
--	TOTAL_LABOR_COST_TAIL_SASHI,
--	TOTAL_LABOR_COST_HARIAWASE,
--	TOTAL_LABOR_COST_ANNEALING,
--	TOTAL_LABOR_COST_HEATSEAL,
--	TOTAL_LABOR_COST_HOKYOTAPE,
--	TOTAL_LABOR_COST_FUREKENSA,
--	TOTAL_LABOR_COST_DENKI,
--	TOTAL_LABOR_COST_DOUBLE_TAPE,
--	TOTAL_LABOR_COST_BARCODE_LABEL,
--	TOTAL_LABOR_COST_GAIKAN_1X,
--	TOTAL_LABOR_COST_GAIKAN_2X
--FROM
--	(
--		SELECT 
--			M.DMC_CODE,
--			M.PART,
--			M.DMC_CODE_PARTS,	
--			CASE WHEN M.PART = 'F' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_F,
--			CASE WHEN M.PART = 'G' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_G,
--			CASE WHEN M.PART = 'T' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_T,
--			CASE WHEN M.PART = 'A' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_A,
--			CASE WHEN M.PART = 'P' THEN SUM(M.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_PER_PCS_P,
--			CASE WHEN M.PART = 'F' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_F,
--			CASE WHEN M.PART = 'G' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_G,
--			CASE WHEN M.PART = 'T' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_T,
--			CASE WHEN M.PART = 'A' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_A,
--			CASE WHEN M.PART = 'P' THEN (MU.PRICE_PER_PCS) ELSE 0 END as AKUMULASI_PRICE_MATERIAL_USAGE_PER_PCS_P					
--		FROM 
--			ad_dis_pc_production_cost_material M

--		LEFT OUTER JOIN
--			(SELECT 
--				DMC_CODE, 
--				DMC_CODE_PARTS,
--				PART,						
--				SUM(PRICE_PER_PCS) as PRICE_PER_PCS
--			FROM
--				ad_dis_pc_production_cost_material_usage
--			WHERE 
--				--SELAIN CHUKAN GLASS & FILM, DENKI TAIL, GAIKAN TAIL, CEK KELENGKAPAN 
--				kode_proses not in (3030, 3040, 3120, 3140, 3155)
--			GROUP BY
--				DMC_CODE, 
--				DMC_CODE_PARTS,
--				PART				
--				) as MU ON M.DMC_CODE = MU.DMC_CODE AND M.DMC_CODE_PARTS = MU.DMC_CODE_PARTS
--		GROUP BY
--			M.DMC_CODE,
--			M.PART,
--			M.DMC_CODE_PARTS,
--			MU.PRICE_PER_PCS
--	) AS [ACC]

----====================================================
----JOIN DENGAN LABOR COST PRINTNG, NON PRINTING, PRESS
----====================================================

--LEFT OUTER JOIN 
--		(
--			SELECT
--				[LC].DMC_CODE,	
--				--SUM([LC].PRICE_PER_PCS) AS PRICE_PER_PCS, 
--				SUM([LC].PRINTING_F) AS LABOR_COST_PRINTING_F,
--				SUM([LC].PRINTING_G) AS LABOR_COST_PRINTING_G,
--				SUM([LC].PRINTING_T) AS LABOR_COST_PRINTING_T,
--				SUM([LC].NON_PRINTING_F) AS LABOR_COST_NON_PRINTING_F,
--				SUM([LC].NON_PRINTING_G) AS LABOR_COST_NON_PRINTING_G,
--				SUM([LC].NON_PRINTING_T) AS LABOR_COST_NON_PRINTING_T,
--				SUM([LC].PRESS_F) AS LABOR_COST_PRESS_F,
--				SUM([LC].PRESS_G) AS LABOR_COST_PRESS_G,
--				SUM([LC].PRESS_T) AS LABOR_COST_PRESS_T,
--				SUM([LC].ETCHING_F) AS LABOR_COST_ETCHING_F,
--				SUM([LC].ETCHING_G) AS LABOR_COST_ETCHING_G
--			FROM(
--					SELECT
--						DMC_CODE,			
--						CASE WHEN C.FACTORY = 'printing' and MU.PART = 'FILM' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRINTING_F,
--						CASE WHEN C.FACTORY = 'printing' and MU.PART = 'GLASS' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRINTING_G,
--						CASE WHEN C.FACTORY = 'printing' and MU.PART = 'TAIL' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRINTING_T,
--						CASE WHEN C.FACTORY = 'non printing' and MU.PART = 'FILM' THEN SUM(PRICE_PER_PCS) ELSE 0 END as NON_PRINTING_F,
--						CASE WHEN C.FACTORY = 'non printing' and MU.PART = 'GLASS' THEN SUM(PRICE_PER_PCS) ELSE 0 END as NON_PRINTING_G,
--						CASE WHEN C.FACTORY = 'non printing' and MU.PART = 'TAIL' THEN SUM(PRICE_PER_PCS) ELSE 0 END as NON_PRINTING_T,
--						CASE WHEN C.FACTORY = 'press' and MU.PART = 'FILM' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRESS_F,
--						CASE WHEN C.FACTORY = 'press' and MU.PART = 'GLASS' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRESS_G,
--						CASE WHEN C.FACTORY = 'press' and MU.PART = 'TAIL' THEN SUM(PRICE_PER_PCS) ELSE 0 END as PRESS_T,
--						CASE WHEN C.FACTORY = 'etching' and MU.PART = 'FILM' THEN SUM(PRICE_PER_PCS) ELSE 0 END as ETCHING_F,
--						CASE WHEN C.FACTORY = 'etching' and MU.PART = 'GLASS' THEN SUM(PRICE_PER_PCS) ELSE 0 END as ETCHING_G
--					FROM
--						ad_dis_pc_production_cost_material_usage MU
--					INNER JOIN
--						[ad_dis_pc_master_chinritsu] C ON MU.KODE_PROSES = C.ID_KOTEI AND SUBSTRING(MU.PART, 1, 1) = C.PART
--					GROUP BY
--					DMC_CODE,
--					MU.PART,
--					KODE_PROSES,
--					C.FACTORY
--			) AS [LC]
--			--WHERE [LC].DMC_CODE = 'TP-4750S1F0'
--			GROUP BY 
--				[LC].DMC_CODE
--		) AS [LC] 
--ON [ACC].DMC_CODE = [LC] .DMC_CODE

----============================================================================
----JOIN DENGAN LABOR COST PROSES CHUK FILM, CHUK GLASS, DENKI TAIL, GAIKAN TAIL
----============================================================================

--LEFT OUTER JOIN 
--		(			
--			SELECT
--				[TLC].DMC_CODE,
--				SUM([TLC].TOTAL_LABOR_COST_CHUKAN_FILM) as TOTAL_LABOR_COST_CHUKAN_FILM,
--				SUM([TLC].TOTAL_LABOR_COST_CHUKAN_GLASS) as TOTAL_LABOR_COST_CHUKAN_GLASS,
--				SUM([TLC].TOTAL_LABOR_COST_DENKI_TAIL) as TOTAL_LABOR_COST_DENKI_TAIL,
--				SUM([TLC].TOTAL_LABOR_COST_GAIKAN_TAIL) as TOTAL_LABOR_COST_GAIKAN_TAIL,
--				SUM([TLC].TOTAL_LABOR_COST_TAIL_SASHI) as TOTAL_LABOR_COST_TAIL_SASHI,
--				SUM([TLC].TOTAL_LABOR_COST_HARIAWASE) as TOTAL_LABOR_COST_HARIAWASE,
--				SUM([TLC].TOTAL_LABOR_COST_ANNEALING) as TOTAL_LABOR_COST_ANNEALING,
--				SUM([TLC].TOTAL_LABOR_COST_HEATSEAL) as TOTAL_LABOR_COST_HEATSEAL,
--				SUM([TLC].TOTAL_LABOR_COST_HOKYOTAPE) as TOTAL_LABOR_COST_HOKYOTAPE,
--				SUM([TLC].TOTAL_LABOR_COST_FUREKENSA) as TOTAL_LABOR_COST_FUREKENSA,
--				SUM([TLC].TOTAL_LABOR_COST_DENKI) as TOTAL_LABOR_COST_DENKI,
--				SUM([TLC].TOTAL_LABOR_COST_DOUBLE_TAPE) as TOTAL_LABOR_COST_DOUBLE_TAPE,
--				SUM([TLC].TOTAL_LABOR_COST_BARCODE_LABEL) as TOTAL_LABOR_COST_BARCODE_LABEL,
--				SUM([TLC].TOTAL_LABOR_COST_GAIKAN_1X) as TOTAL_LABOR_COST_GAIKAN_1X,
--				SUM([TLC].TOTAL_LABOR_COST_GAIKAN_2X) as TOTAL_LABOR_COST_GAIKAN_2X
--			FROM 
--					(
--						SELECT 
--							DMC_CODE,
--							NAMA_PROSES,		
--							CASE WHEN NAMA_PROSES like 'Chukan Film' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_CHUKAN_FILM,
--							CASE WHEN NAMA_PROSES like 'Chukan Glass' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_CHUKAN_GLASS,
--							CASE WHEN NAMA_PROSES like 'Denki Tail' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_DENKI_TAIL,
--							CASE WHEN NAMA_PROSES like 'Gaikan Tail' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_GAIKAN_TAIL,
--							CASE WHEN NAMA_PROSES like 'Tail Sashi' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_TAIL_SASHI,
--							CASE WHEN NAMA_PROSES like 'Hariawase' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_HARIAWASE,
--							CASE WHEN NAMA_PROSES like 'Annealing' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_ANNEALING,
--							CASE WHEN NAMA_PROSES like 'FPC/Jogekan Heatseal' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_HEATSEAL,
--							CASE WHEN NAMA_PROSES like 'Hokyotape' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_HOKYOTAPE,
--							CASE WHEN NAMA_PROSES like 'Fure kensa' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_FUREKENSA,
--							CASE WHEN NAMA_PROSES like 'Denki 1x' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_DENKI,							
--							CASE WHEN NAMA_PROSES like 'Double Tape' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_DOUBLE_TAPE,
--							CASE WHEN NAMA_PROSES like 'Assy Barcode Label' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_BARCODE_LABEL,
--							CASE WHEN NAMA_PROSES like 'Gaikan 1x' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_GAIKAN_1X,
--							CASE WHEN NAMA_PROSES like 'Gaikan 2x' THEN sum(price_per_pcs) ELSE 0 END as TOTAL_LABOR_COST_GAIKAN_2X
--						FROM
--							ad_dis_pc_production_cost_material_usage MU	
--						GROUP BY 
--							dmc_code,nama_proses
--					) AS [TLC]	
--					GROUP BY [TLC].DMC_CODE
--			) AS [TLC]
--ON [ACC].DMC_CODE = [TLC] .DMC_CODE

----============================================================================
----JOIN TRANSPORTATION COST
----============================================================================

--LEFT OUTER JOIN 
--		(
--			SELECT	
--				item_code,
--				case when TR.jenis_transportation LIKE '%Trans Cost Air JPN%' then TR.total_cost else 0 end as AIR_JPN,	
--				case when TR.jenis_transportation LIKE '%Trans Cost Sea Tokyo%' then TR.total_cost else 0 end as SEA_TOKYO,
--				case when TR.jenis_transportation LIKE '%Trans Cost Air Sha%' then TR.total_cost else 0 end as AIR_SHA,
--				case when TR.jenis_transportation LIKE '%Trans Cost Sea Sha%' then TR.total_cost else 0 end as SEA_SHA,
--				case when TR.jenis_transportation LIKE '%Trans Cost Air Hkg%' then TR.total_cost else 0 end as AIR_HKG,
--				case when TR.jenis_transportation LIKE '%Trans Cost Sea Hkg%' then TR.total_cost else 0 end as SEA_HKG
--			FROM
--				ad_dis_pc_master_transportation TR
--			WHERE 
--				item_code like 'TP-4750S1F0'
--		) AS [TR]
--ON [ACC].DMC_CODE = [TR].item_code
----WHERE [ACC].DMC_CODE = 'TP-4750S1F0'
--WHERE [ACC].DMC_CODE = @DMC_CODE

--GROUP BY 
--	[ACC].DMC_CODE, 	
--	LABOR_COST_PRINTING_F,
--	LABOR_COST_PRINTING_G, 
--	LABOR_COST_PRINTING_T,
--	LABOR_COST_NON_PRINTING_F,
--	LABOR_COST_NON_PRINTING_G,
--	LABOR_COST_NON_PRINTING_T,
--	LABOR_COST_PRESS_F,
--	LABOR_COST_PRESS_G,
--	LABOR_COST_PRESS_T,
--	LABOR_COST_ETCHING_F,
--	LABOR_COST_ETCHING_G,
--	TOTAL_LABOR_COST_CHUKAN_FILM,
--	TOTAL_LABOR_COST_CHUKAN_GLASS,
--	TOTAL_LABOR_COST_DENKI_TAIL,
--	TOTAL_LABOR_COST_GAIKAN_TAIL,
--	TOTAL_LABOR_COST_TAIL_SASHI,
--	TOTAL_LABOR_COST_HARIAWASE,
--	TOTAL_LABOR_COST_ANNEALING,
--	TOTAL_LABOR_COST_HEATSEAL,
--	TOTAL_LABOR_COST_HOKYOTAPE,
--	TOTAL_LABOR_COST_FUREKENSA,
--	TOTAL_LABOR_COST_DENKI,
--	TOTAL_LABOR_COST_DOUBLE_TAPE,
--	TOTAL_LABOR_COST_BARCODE_LABEL,
--	TOTAL_LABOR_COST_GAIKAN_1X,
--	TOTAL_LABOR_COST_GAIKAN_2X
