SELECT 
    ROW_NUMBER() OVER (order by dmc_type ASC) ROW_NUM
	,[dmc_type] as ID 
	,[dmc_type]
    ,[air_cif_sales_price]
    ,[air_cif_material_cost]
    ,[air_cif_labour_cost]
    ,[air_cif_indirect]
    ,[air_cif_sga]
    ,[air_cif_transportation_cost]
    ,[air_cif_grand_total]
    ,[air_cif_marginal_profit_ratio]
    ,[air_cif_profit_ratio]
    ,[fob_sales_price]
    ,[fob_material_cost]
    ,[fob_labour_cost]
    ,[fob_indirect]
    ,[fob_sga]
    ,[fob_transportation_cost]
    ,[fob_grand_total]
    ,[fob_marginal_profit_ratio]
    ,[fob_profit_ratio]
    ,[labour_cost_printing]
    ,[labour_cost_assembly]
    ,[labour_cost_etching]
    ,[labour_cost_press]
    ,[labour_cost_non_printing]
    ,[labour_cost_kompo]
    ,[material_cost_after_gaikan]
    ,[labour_cost_printing_after_gaikan]
    ,[labour_cost_assembly_after_gaikan]
    ,[labour_cost_etching_after_gaikan]
    ,[labour_cost_press_after_gaiakan]
    ,[labour_cost_non_printing_after_gaikan]
FROM [TxDTIPRD].[dbo].[ad_dis_pc_sales_price]
WHERE dmc_type = @ID

