select  wp.ID as TB_R_WP_DAILY_ID, 
		wd.ID as TB_R_WP_DAILY_WORKER_LIST_ID, 
		wd.TB_M_EMPLOYEE_ID,
		(SELECT TOP 1 IDENTITY_NO FROM TB_M_EMPLOYEE WHERE ID_TB_M_EMPLOYEE = wd.TB_M_EMPLOYEE_ID) NIK,
		(select itm.FIRST_NAME from TB_M_EMPLOYEE itm where itm.ID_TB_M_EMPLOYEE = wd.TB_M_EMPLOYEE_ID) as FIRST_NAME
from TB_R_WP_DAILY wp 
left join TB_R_WP_DAILY_WORKER_LIST wd 
on wd.TB_R_WP_DAILY_ID = wp.ID
where wp.ID = @WP_DAILY_ID