DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
BEGIN TRY
	UPDATE TB_M_ROLE SET ROLE_NAME = @ROLE_NAME, ROLE_ST = @ROLE_ST, ROLE_DESC = @ROLE_DESC, ID_TB_M_AUTHORIZATION_FUNCTION = @AUTH, SESSION_TIME_OUT = @SESSION_TIME_OUT, LOCK_TIME_OUT = @LOCK_TIME_OUT, UPDATED_BY = @USERNAME, UPDATED_DT = GETDATE() WHERE ID_TB_M_ROLE = @ID
	SET @@CHK = 'TRUE';
	SET @@ERR = 'Data Has Been Updated';
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR UPDATE TB_M_ROLE:' +@ROLE_NAME+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS