DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@DATA_ID VARCHAR(MAX) = @DATA_ID;
DECLARE @@TIME_UNIT_CRITERIA VARCHAR(MAX) = @TIME_UNIT_CRITERIA;
DECLARE @@EXECUTION_TIME VARCHAR(MAX) = @EXECUTION_TIME;
DECLARE @@STATUS_ACTIVE VARCHAR(MAX) = @STATUS_ACTIVE;

SET @@QUERY = '';
SET @@QUERY = '
	SELECT ISNULL(max(ROW_NUM),0) FROM 
	(
		SELECT ROW_NUMBER() OVER (ORDER BY A.ID_TB_M_LOCATION ASC) ROW_NUM,
		A.ID_TB_M_LOCATION AS ID,
		B.AREA_NAME,
		B.ID_TB_M_AREA AS AREA_ID,
		B.AREA_CD,
		A.LOC_CD,
		A.LOC_NAME,
		A.STATUS,
		A.CREATE_BY,
		A.CREATE_DT,
		A.UPDATE_BY,
		A.UPDATE_DT
		FROM TB_M_LOCATION AS A INNER JOIN TB_M_AREA AS B ON A.ID_TB_M_AREA = B.ID_TB_M_AREA
		WHERE 1=1 AND A.IS_DELETED = 0
';

IF(@AREA_CODE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.ID_TB_M_AREA LIKE ''%'+RTRIM(@AREA_CODE)+'%'' ';
	END

IF(@LOC_NAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.LOC_NAME LIKE ''%'+RTRIM(@LOC_NAME)+'%'' ';
	END

IF(@LOC_CODE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.LOC_CD LIKE ''%'+RTRIM(@LOC_CODE)+'%'' ';
	END

SET @@QUERY = @@QUERY +') as TB';


EXEC(@@QUERY);

