DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@START VARCHAR(50) = @START;
DECLARE @@DISPLAY VARCHAR(50) = @DISPLAY;
SET @@QUERY = '';
SET @@QUERY = 'SELECT * 
			   FROM(
					select  ROW_NUMBER() OVER (ORDER BY wp.ID ASC) ROW_NUM, 
							wp.ID as WP_DAILY_ID, 
							wp.TB_R_WP_PROJECT_ID AS PROJECT_ID, 
							wp.TB_R_WP_PROJECT_JOB_ID as PROJECT_JOB_ID, 
							pr.PROJECT_NAME, 
							pr.IMPLEMENT_DATE_FROM as DATE_FROM, 
							pr.IMPLEMENT_DATE_TO as DATE_TO, 
							ar.AREA_NAME as PROJECT_LOCATION, 
							pr.DEP_OR_DIV_CODE as DIVISI,
							wp.CREATE_BY,
							wp.CREATE_DT,
							wp.TITLE,
							PJ.CREATED_BY,
							PJ.CREATED_DT,
							PJ.CHANGED_BY,
							PJ.CHANGED_DT,
							PJ.WP_IMPB_NO
					from TB_R_WP_DAILY wp 
					INNER JOIN TB_R_WP_PROJECT_JOB AS PJ ON PJ.ID = wp.TB_R_WP_PROJECT_JOB_ID
					INNER JOIN TB_R_WP_PROJECT pr ON pr.ID = PJ.WP_PROJECT_ID
					left join TB_M_AREA ar 
					on ar.ID_TB_M_AREA = pr.ID_TB_M_AREA 
					WHERE 1=1 and wp.ACTIVE = 1  ';
IF(@PROJECT_NAME <> '')
BEGIN
	SET @@QUERY = @@QUERY + 'AND PROJECT_NAME LIKE ''%'+@PROJECT_NAME+'%'' ';
END

SET @@QUERY = @@QUERY +') as TB';

IF(@@START > 0 AND @@DISPLAY > 0)
BEGIN	
	SET @@QUERY = @@QUERY +' WHERE ROW_NUM BETWEEN '+@@START+' AND '+@@DISPLAY;
END

EXEC(@@QUERY)