SELECT  A.ID,
		A.WP_PROJECT_ID,
		A.JOB_NAME,
		A.WP_IMPB_NO,
		B.IMPLEMENT_DATE_FROM,
		B.IMPLEMENT_DATE_TO
FROM TB_R_WP_PROJECT_JOB A INNER JOIN TB_R_WP_PROJECT B ON A.WP_PROJECT_ID = B.ID
WHERE A.WP_PROJECT_ID=@WP_PROJECT_ID  AND (A.JOB_STATUS != '' AND A.JOB_STATUS != 'DRAFT')
AND CONVERT(DATE, A.START_DATE) <= CONVERT(DATE, GETDATE()) AND CONVERT(DATE, A.END_DATE) >= CONVERT(DATE, GETDATE());
--AND CONVERT(VARCHAR(MAX),B.ID)+':'+CONVERT(VARCHAR(MAX),A.ID) NOT IN (SELECT CONVERT(VARCHAR(MAX),TB_R_WP_PROJECT_ID)+':'+CONVERT(VARCHAR(MAX),TB_R_WP_PROJECT_JOB_ID) FROM TB_R_WP_DAILY);

