DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);
DECLARE @@CHK_DELETE VARCHAR(5);
BEGIN TRY
	SET @@CNT = (SELECT COUNT(1) FROM TB_M_EMPLOYEE WHERE IDENTITY_NO = @IDENTITY_NO AND REG_NO = @REGNUMBER);
	SET @@ERR = @@CNT;
	IF(@@CNT > 0)
	BEGIN
		
			UPDATE TB_M_EMPLOYEE SET 
				[ID_TB_M_COMPANY] = @COMPANY
				,[REG_NO] = @REGNUMBER
				,[FIRST_NAME] = @FIRSTNAME
				,[LAST_NAME] = @LASTNAME
				,[EMAIL] = @EMAIL
				,[SECTION] = @SECTION
				,[ADDRESS] = @ADDRESS
				,[PHONE] = @PHONE
				,[IDENTITY_TYPE] = 'KTP'
				,[IDENTITY_NO] = @IDENTITY_NO
				,[PIC_STATUS] = 'MEM'
				,[ANZEN_SERTIFICATE_NO] = @ANZEN_NO
				,[ANZEN_DT_FROM] = @ANZEN_DT_FROM
				,[ANZEN_DT_TO] = @ANZEN_DT_TO
				,[SAFETY_INDUCTION_NO] = @SAFETY_INDUCTION_NO
				,[SAFETY_INDUCTION_FROM] = @SAFETY_INDUCTION_FROM
				,[SAFETY_INDUCTION_TO] = @SAFETY_INDUCTION_TO
				,[GENDER] = @GENDER
				,[UPDATE_BY] = @username
				,[UPDATE_DT] = GETDATE()
				,[IS_DELETED] = 0
			WHERE IDENTITY_NO = @IDENTITY_NO;

			SET @@CHK = 'TRUE';
			SET @@ERR = 'Success';
		
		
	END ELSE
	BEGIN
		
		INSERT INTO TB_M_EMPLOYEE
		(
			 [ID_TB_M_COMPANY]
			,[REG_NO]
			,[FIRST_NAME]
			,[LAST_NAME]
			,[EMAIL]
			,[SECTION]
			,[ADDRESS]
			,[PHONE]
			,[IDENTITY_TYPE]
			,[IDENTITY_NO]
			,[PIC_STATUS]
			,[ANZEN_SERTIFICATE_NO]
			,[SAFETY_INDUCTION_NO]
			,[SAFETY_INDUCTION_FROM]
			,[SAFETY_INDUCTION_TO]
			,[GENDER]
			,[CREATE_BY]
			,[CREATE_DT]
			,[UPDATE_BY]
			,[UPDATE_DT]
			
		)
		VALUES
		(
			@COMPANY,
			@REGNUMBER,
			@FIRSTNAME,
			@LASTNAME,
			@EMAIL,
			@SECTION,
			@ADDRESS,
			@PHONE,
			'KTP',
			@IDENTITY_NO,
			'MEM',
			@ANZEN_NO,
			@SAFETY_INDUCTION_NO,
			@SAFETY_INDUCTION_FROM,
			@SAFETY_INDUCTION_TO,
			--@SEQ_NO,
			--@STATUS,
			@GENDER,
			@username,
			GETDATE(),
			@username,
			GETDATE()
		);


		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';
	END
	SET @@ERR = @@CNT;
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR TB_M_EMPLOYEE: ' +@IDENTITY_NO+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS