DECLARE @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);
BEGIN TRY
	INSERT INTO TB_R_WP_DAILY
	(
		[ID]
		,[TB_R_WP_PROJECT_ID]
		,[TB_R_WP_PROJECT_JOB_ID]
		,[TITLE]
		,[DAILY_DOC]
		,[CREATE_BY]
		,[CREATE_DT]
		,[UPDATE_BY]
		,[UPDATE_DT]
		,[STATUS]
	)
	VALUES
	(
		@TB_R_WP_DAILY_ID,
		@WP_PROJECT_ID,
		@WP_PROJECT_JOB_ID,
		@JOB_TITLE,
		@DAILY_DOC,
		@username,
		GETDATE(),
		@username,
		GETDATE(),
		@STATUS
	);

	SET @@CHK = 'TRUE';
	SET @@ERR = 'NOTHING';
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR INSERT TB_R_WP_DAILY:' +@TB_R_WP_DAILY_ID+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS