DECLARE @@STATUS_EMPLOYEE VARCHAR(100);

SET @@STATUS_EMPLOYEE = (select SECTION from tb_m_employee where USERNAME = @USERNAME);

IF(@@STATUS_EMPLOYEE = 'GENERAL')
BEGIN
	SELECT A.ID,A.PROJECT_CODE,A.PROJECT_NAME FROM TB_R_WP_PROJECT  A
	INNER JOIN TB_R_WP_PROJECT_JOB B ON A.ID = B.WP_PROJECT_ID
	INNER JOIN TB_R_WP_DETAIL_IMPLEMENTOR AS C ON C.WP_PROJECT_JOB_ID = B.ID
	WHERE A.PROJECT_STATUS='SUBMITED' AND B.JOB_STATUS='SUBMITED'
	AND A.IMPLEMENT_DATE_TO >= GETDATE() 
	AND C.EMPLOYEE_LEAD_PROJECT = @ID
	AND C.WP_PROJECT_JOB_ID NOT IN (select TB_R_WP_PROJECT_JOB_ID from TB_R_WP_DAILY WHERE CONVERT(DATE, CREATE_DT) = CONVERT(DATE, GETDATE()) AND TB_R_WP_PROJECT_JOB_ID IS NOT NULL);
END
ELSE
BEGIN
	SELECT A.ID,A.PROJECT_CODE,A.PROJECT_NAME FROM TB_R_WP_PROJECT  A
	INNER JOIN TB_R_WP_PROJECT_JOB B ON A.ID = B.WP_PROJECT_ID
	INNER JOIN TB_R_WP_DETAIL_IMPLEMENTOR AS C ON C.WP_PROJECT_JOB_ID = B.ID
	WHERE A.PROJECT_STATUS='SUBMITED' AND B.JOB_STATUS='SUBMITED'
	AND A.IMPLEMENT_DATE_TO >= GETDATE()
	AND C.WP_PROJECT_JOB_ID NOT IN (select TB_R_WP_PROJECT_JOB_ID from TB_R_WP_DAILY WHERE CONVERT(DATE, CREATE_DT) = CONVERT(DATE, GETDATE()) AND TB_R_WP_PROJECT_JOB_ID IS NOT NULL);
END
