DELETE TB_R_WP_DAILY WHERE ID = @ID

DELETE TB_R_WP_DAILY_APD WHERE TB_R_WP_DAILY_ID = @ID;

DELETE TB_R_WP_DAILY_UTIL_REQUEST WHERE TB_R_WP_DAILY_ID = @ID;

DELETE TB_R_WP_DAILY_WI_DEN WHERE TB_R_WP_DAILY_ID = @ID;

DELETE TB_R_WP_DAILY_WORK_EQUIPMENT WHERE TB_R_WP_DAILY_ID = @ID;

DELETE TB_R_WP_DAILY_WORKER_LIST WHERE TB_R_WP_DAILY_ID = @ID;
