SELECT SUBSTRING(S.SYSTEM_VALUE_TXT, 1, CHARINDEX('(', S.SYSTEM_VALUE_TXT) -1) as SHIFT FROM TB_M_SYSTEM S
  INNER JOIN TB_R_WP_DETAIL_SHIFT DS
  ON DS.SHIFT_ID = S.SYSTEM_VALUE_NUM
  WHERE S. SYSTEM_ID='WP_WORKING_HOURS' AND DS.WP_PROJECT_JOB_ID = @PROJECT_JOB_ID