DECLARE @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);
BEGIN TRY
	UPDATE TB_R_WP_DAILY
	SET TITLE = @JOB_TITLE,
	DAILY_DOC = @DAILY_DOC,
	TB_R_WP_PROJECT_ID = @WP_PROJECT_ID,
	TB_R_WP_PROJECT_JOB_ID = @WP_PROJECT_JOB_ID,
	UPDATE_BY = @username,
	UPDATE_DT = GETDATE()
	WHERE ID = @TB_R_WP_DAILY_ID;

	SET @@CHK = 'TRUE';
	SET @@ERR = 'NOTHING';
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR INSERT TB_R_WP_DAILY:' +@TB_R_WP_DAILY_ID+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS