DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);

BEGIN TRY
	SET @@CNT = (SELECT COUNT(1) FROM TB_M_AUTHORIZATION_FUNCTION WHERE AUTHORIZATION_NAME = @AUTHORIZATION_NAME);
	IF(@@CNT > 0)
	BEGIN
		SET @@CHK = 'FALSE';
		SET @@ERR = 'Data Has been Registered';
		
	END ELSE
	BEGIN
		
		INSERT INTO TB_M_AUTHORIZATION_FUNCTION
		(
			 [AUTHORIZATION_NAME]
			,[AUTHORIZATION_DESC]
			,[ID_MENU]
			,[ID_MENU_PARENT]
			,[CREATED_BY]
			,[CREATED_DT]
			,[UPDATED_BY]
			,[UPDATED_DT]
			,[IS_DELETED]
		)
		VALUES
		(
			@AUTHORIZATION_NAME,
			@AUTHORIZATION_DESC,
			@MENUS,
			@MENUS_PARENT,
			@USERNAME,
			GETDATE(),
			@USERNAME,
			GETDATE(),
			0
		);


		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';
	END
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR INSERT TB_M_AUTHORIZATION_FUNCTION:' +@AUTHORIZATION_NAME+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS