DECLARE @@DATE VARCHAR(MAX);
SET @@DATE = (SELECT TOP 1 DATE FROM TB_R_WP_SECURITY_CHECK WHERE (CHECK_OUT = '' OR CHECK_OUT IS NULL) ORDER BY DATE ASC);
--GET Incident

IF(@@DATE IS NOT NULL)
BEGIN
	SELECT  COUNT(ID_TB_M_COMPANY) FROM 
	(SELECT DISTINCT ID_TB_M_COMPANY 
	FROM TB_R_WP_DETAIL_IMPLEMENTOR AS A
	INNER JOIN TB_R_WP_PROJECT_JOB AS B ON A.WP_PROJECT_JOB_ID = B.ID
	INNER JOIN TB_R_WP_PROJECT AS C ON B.WP_PROJECT_ID = C.ID
	WHERE C.ID_TB_M_AREA = @AREA
	AND CONVERT(date, @@DATE) >= CONVERT(date, C.IMPLEMENT_DATE_FROM) AND CONVERT(date, getdate()) <= CONVERT(date, C.IMPLEMENT_DATE_TO) 
	) AS TB 
	WHERE ID_TB_M_COMPANY IS NOT NULL AND ID_TB_M_COMPANY != 0
END
ELSE
BEGIN
	SELECT  COUNT(ID_TB_M_COMPANY) FROM 
	(SELECT DISTINCT ID_TB_M_COMPANY 
	FROM TB_R_WP_DETAIL_IMPLEMENTOR AS A
	INNER JOIN TB_R_WP_PROJECT_JOB AS B ON A.WP_PROJECT_JOB_ID = B.ID
	INNER JOIN TB_R_WP_PROJECT AS C ON B.WP_PROJECT_ID = C.ID
	WHERE C.ID_TB_M_AREA = @AREA
	AND CONVERT(date, getdate()) >= CONVERT(date, C.IMPLEMENT_DATE_FROM) AND CONVERT(date, getdate()) <= CONVERT(date, C.IMPLEMENT_DATE_TO) 
	) AS TB 
	WHERE ID_TB_M_COMPANY IS NOT NULL AND ID_TB_M_COMPANY != 0
END