SELECT *
FROM (
	SELECT R.ID_TB_R_LEARN_EXAM_QUESTION AS [Id]
		,ROW_NUMBER() OVER (ORDER BY R.ID_TB_R_LEARN_EXAM_QUESTION DESC) AS [No]
		,R.ID_TB_R_LEARN_EXAM_SUBJECT AS [SubjectId]
		,R.ID_TB_M_LEARN_QUESTION AS [QuestionId]
		,S.TITLE
		,Q.QUESTION
		,Q.ANSWER_CHOICE_A
		,Q.ANSWER_CHOICE_B
		,Q.ANSWER_CHOICE_C
		,Q.ANSWER_CHOICE_D
		,Q.ANSWER_CHOICE_E
		,Q.ANSWER_KEY
		,R.CREATED_BY
		,R.CREATED_DT
		,R.UPDATED_BY
		,R.UPDATED_DT
	FROM TB_R_LEARN_EXAM_QUESTION AS R
		LEFT JOIN TB_R_LEARN_EXAM_SUBJECT AS S 
			ON R.ID_TB_R_LEARN_EXAM_SUBJECT = S.ID_TB_R_LEARN_EXAM_SUBJECT
		LEFT JOIN TB_M_LEARN_QUESTION AS Q
			ON R.ID_TB_M_LEARN_QUESTION = Q.ID_TB_M_LEARN_QUESTION
	WHERE R.IS_DELETED = 0 
		AND (S.ID_TB_R_LEARN_EXAM_SUBJECT = @subjectId OR @subjectId = 0 )) AS [BASE]
WHERE ((@pageNumber - 1) * @display) < [BASE].[No] AND [BASE].[No] < (@display + ((@pageNumber - 1) * @display))
ORDER BY [BASE].[No] ASC