DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@START VARCHAR(50) = @START;
DECLARE @@DISPLAY VARCHAR(50) = @DISPLAY;


SET @@QUERY = '';
SET @@QUERY = 'SELECT * FROM ( SELECT ROW_NUMBER() OVER (ORDER BY ID ASC) ROW_NUM,
		ID,
       PROJECT_CODE,
       PROJECT_NAME,
       ID_TB_M_AREA,
       AREA_NAME,
       ID_TB_M_LOCATION,
       LOC_NAME,
       DEP_OR_DIV_CODE,
       IMPLEMENT_DATE_FROM,
       IMPLEMENT_DATE_TO,
       IMPLEMENT_DATE_FROM_DISP,
       IMPLEMENT_DATE_TO_DISP,
       WORKING_STATUS_DESC,
       WORKING_STATUS,
       WORKING_NOTES,
       PROJECT_STATUS,
       CREATED_BY,
       CREATED_DT,
       CHANGED_BY,
       CHANGED_DT
    FROM dbo.VW_PROJECT_REGISTRATION
    WHERE 1=1 ';

IF(@PROJECT_NAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND PROJECT_NAME LIKE ''%'+@PROJECT_NAME+'%'' ';
	END

IF(@PROJECT_LOCATION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TB_M_LOCATION = '''+@PROJECT_LOCATION+''' ';
	END

IF(@PROJECT_DATE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IMPLEMENT_DATE_FROM >= '''+@PROJECT_DATE+''' ';
	END

IF(@PROJECT_DATETO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IMPLEMENT_DATE_TO <= '''+@PROJECT_DATETO+''' ';
	END

IF(@DIVISION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND DEP_OR_DIV_CODE = '''+@DIVISION+''' ';
	END

IF(@STATUS <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND WORKING_STATUS_DESC LIKE ''%'+@STATUS+'%'' ';
	END

SET @@QUERY = @@QUERY +') as TB';

IF(@@START > 0 AND @@DISPLAY > 0)
BEGIN	
	SET @@QUERY = @@QUERY +' WHERE ROW_NUM BETWEEN '+@@START+' AND '''+@@DISPLAY+''' ';
END

EXEC(@@QUERY)