DECLARE @@IMPLEMENTOR VARCHAR(MAX);
DECLARE @@WP_PROJECT_JOB_ID VARCHAR(MAX);
DECLARE @@IMPB VARCHAR(MAX);
DECLARE @@EMPLOYEE_ID VARCHAR(MAX);

SELECT TOP 1 ID_TB_M_EMPLOYEE AS ID, REG_NO, ANZEN_SERTIFICATE_NO, ANZEN_DT_FROM, ANZEN_DT_TO, SAFETY_INDUCTION_NO, SAFETY_INDUCTION_FROM AS VALID_DARI, SAFETY_INDUCTION_TO AS VALID_SAMPAI, FIRST_NAME, LAST_NAME, IDENTITY_NO AS NO_IDENTITY, IDENTITY_TYPE, ADDRESS, 
EMAIL , 
(SELECT TOP 1 FIRST_NAME + ' ' + LAST_NAME FROM TB_M_EMPLOYEE WHERE ANZEN_SERTIFICATE_NO = TB_M_EMPLOYEE.ANZEN_SERTIFICATE_NO AND PIC_STATUS = 'PMP') AS ANZEN_LEADER,
(
CASE WHEN ISNUMERIC(TB_M_EMPLOYEE.SECTION) = 1 THEN
	(SELECT TOP 1 DIV FROM [dbo].[TB_M_ORG_RANK] where DIV_ID is not null AND DIV_ID = TB_M_EMPLOYEE.SECTION)
 ELSE
    'GENERAL'
 END
) AS SECTION,
PHONE, PIC_STATUS, EMAIL, GENDER, ADDRESS,
(SELECT TOP 1 COMPANY_NAME FROM TB_M_COMPANY WHERE ID_TB_M_COMPANY = ID_TB_M_COMPANY) AS COMPANY
FROM TB_M_EMPLOYEE WHERE IDENTITY_NO = @scanQR;