DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@START VARCHAR(50) = @START;
DECLARE @@DISPLAY VARCHAR(50) = @DISPLAY;


SET @@QUERY = '';
SET @@QUERY = 'SELECT 
	*
 FROM 
(
	SELECT ROW_NUMBER() OVER (ORDER BY P.ID ASC) ROW_NUM
      ,P.[ID]
	  ,[WP_PROJECT_ID]
      ,[JOB_NAME]
      ,[WP_PROJECT_JOB_ID]
      ,P.[WP_IMPB_NO]
      ,(CASE WHEN 
			(SELECT TOP 1 AREA_ST FROM TB_M_AREA WHERE ID_TB_M_AREA = P.ID_TB_M_AREA) = 2  THEN
			''NON ACTIVE''
		ELSE
			[JOB_STATUS]
		END
		) AS JOB_STATUS
      ,[PROJECT_CODE]
      ,[PROJECT_NAME]
      ,[ID_TB_M_AREA]
      ,[AREA_NAME]
      ,[ID_TB_M_LOCATION]
      ,[LOC_NAME]
      ,[DEP_OR_DIV_CODE]
      ,CONVERT(VARCHAR,[IMPLEMENT_DATE_FROM],126) AS IMPLEMENT_DATE_FROM
      ,CONVERT(VARCHAR, [IMPLEMENT_DATE_TO],126) AS IMPLEMENT_DATE_TO
      ,[IMPLEMENT_DATE_FROM_DISP]
      ,[IMPLEMENT_DATE_TO_DISP]
      ,[WORKING_STATUS_DESC]
      ,[WORKING_STATUS]
      ,[WORKING_NOTES]
      ,[PROJECT_STATUS]
      ,[EXECUTOR]
      ,[EXECUTOR_DESC]
      ,[ID_TB_M_COMPANY]
      ,[COMPANY_NAME]
      ,[EMPLOYEE_LEAD_PROJECT]
      ,[LEADER_NAME]
      ,[EMPLOYEE_SUPERVISOR_PROJECT]
      ,[SUPERVISOR_NAME]
      ,[CREATED_BY]
      ,[CREATED_DT]
      ,[CHANGED_BY]
      ,[CHANGED_DT]
      ,[IMAGE_PATH]
      ,[DIV]
       ,ISNULL(WF.ID, 0) as WFID
  FROM [dbo].[VW_PROJECT_JOB] P
  LEFT JOIN TB_R_WP_WORKFLOW WF ON P.WP_IMPB_NO = WF.WP_IMPB_NO
  WHERE 1=1 AND JOB_STATUS=''APPROVAL'' 
';

IF(@PROJECT_CODE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND PROJECT_CODE LIKE ''%'+@PROJECT_CODE+'%'' ';
	END

IF(@PROJECT_NAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND PROJECT_NAME LIKE ''%'+@PROJECT_NAME+'%'' ';
	END

IF(@LOCATION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TB_M_LOCATION = '''+@LOCATION+''' ';
	END

IF(@DATE_FROM <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IMPLEMENT_DATE_FROM >= '''+@DATE_FROM+''' ';
	END

IF(@DATE_TO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IMPLEMENT_DATE_TO <= '''+@DATE_TO+''' ';
	END

IF(@DIVISION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND DEP_OR_DIV_CODE = '''+@DIVISION+''' ';
	END

IF(@COMPANY <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TB_M_COMPANY = '''+@COMPANY+''' ';
	END

IF(@WP_IMPB_NO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND WP_IMPB_NO = '''+@WP_IMPB_NO+''' ';
	END

SET @@QUERY = @@QUERY +') as TB';

IF(@@START > 0 AND @@DISPLAY > 0)
BEGIN	
	SET @@QUERY = @@QUERY +' WHERE ROW_NUM BETWEEN '+@@START+' AND '''+@@DISPLAY+''' ';
END

EXEC(@@QUERY)