DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@DATA_ID VARCHAR(MAX) = @DATA_ID;
DECLARE @@TIME_UNIT_CRITERIA VARCHAR(MAX) = @TIME_UNIT_CRITERIA;
DECLARE @@EXECUTION_TIME VARCHAR(MAX) = @EXECUTION_TIME;
DECLARE @@STATUS_ACTIVE VARCHAR(MAX) = @STATUS_ACTIVE;

SET @@QUERY = '';
SET @@QUERY = '
	SELECT ISNULL(max(ROW_NUM),0) FROM 
	(
		SELECT ROW_NUMBER() OVER (ORDER BY A.ID_TB_M_EMPLOYEE ASC) ROW_NUM,
	A.ID_TB_M_EMPLOYEE AS ID,
	C.COMPANY_NAME AS COMPANY,
	C.ID_TB_M_COMPANY,
	A.FIRST_NAME,
	A.USERNAME,
	A.PASSWORD,
	A.EMAIL,
	A.ADDRESS,
	A.PIC_STATUS,
	A.PHONE,
	A.IDENTITY_TYPE,
	A.IDENTITY_NO,
	A.ANZEN_SERTIFICATE_NO,
	CONVERT(VARCHAR(16), A.ANZEN_DT_FROM, 120) AS ANZEN_DT_FROM,
	CONVERT(VARCHAR(16), A.ANZEN_DT_TO, 120) AS ANZEN_DT_TO,
	A.SAFETY_INDUCTION_NO,
	CONVERT(VARCHAR(16),A.SAFETY_INDUCTION_FROM, 120) AS SAFETY_INDUCTION_FROM,
	CONVERT(VARCHAR(16),A.SAFETY_INDUCTION_TO, 120) AS SAFETY_INDUCTION_TO,
	A.STATUS,
	A.SECTION,
	A.CREATE_BY,
	A.CREATE_DT,
	A.UPDATE_BY,
	A.UPDATE_DT,
	A.IS_DELETED
	FROM TB_M_EMPLOYEE AS A	
	LEFT JOIN TB_M_COMPANY AS C ON A.ID_TB_M_COMPANY = C.ID_TB_M_COMPANY
	WHERE 1=1
	AND (A.IS_DELETED != 1 OR A.IS_DELETED IS NULL)
	
';

IF(@EMPLOYEE_NAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND (A.FIRST_NAME + '' '' + A.LAST_NAME ) LIKE ''%'+RTRIM(@EMPLOYEE_NAME)+'%'' ';
	END

IF(@IDENTITYNUMBER <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND IDENTITY_NO LIKE ''%'+RTRIM(@IDENTITYNUMBER)+'%'' ';
	END

IF(@COMPANY <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.ID_TB_M_COMPANY LIKE ''%'+RTRIM(@COMPANY)+'%'' ';
	END

IF(@ANZENNO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.ANZEN_SERTIFICATE_NO LIKE ''%'+RTRIM(@ANZENNO)+'%'' ';
	END

IF(@INDUCTION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.SAFETY_INDUCTION_NO LIKE ''%'+RTRIM(@INDUCTION)+'%'' ';
	END

SET @@QUERY = @@QUERY+ ') AS TB';


EXEC(@@QUERY);

