SELECT 
	A.ID_TB_R_LEARN_EXAM_SUBJECT AS Id
	,A.TITLE AS Title
    ,A.PASSING_SCORE_REQUIREMENT
    ,A.EXAM_DURATION AS ExamDuration
    ,A.DATE_EXAM_PERIOD_START AS ExamPeriodStart
    ,A.DATE_EXAM_PERIOD_END AS ExamPeriodEnd
    ,A.REMEDIAL AS MaxRemedial
	,B.NREMEDIAL AS Remedial
    ,A.EXAM_TYPE AS ExamType
FROM 
	TB_R_LEARN_EXAM_SUBJECT AS A
	LEFT JOIN (
				SELECT 
					ID_TB_R_LEARN_EXAM_SUBJECT
					,COUNT(*) AS NREMEDIAL 
				FROM 
					TB_R_LEARN_EXAM_SCORE 
				WHERE 
					ID_TB_M_EMPLOYEE = @EMPLOYEID 
				GROUP BY 
					ID_TB_R_LEARN_EXAM_SUBJECT
			  ) AS B ON A.ID_TB_R_LEARN_EXAM_SUBJECT = B.ID_TB_R_LEARN_EXAM_SUBJECT
WHERE 
	IS_DELETED = 0 
	AND A.IS_PUBLISHED = 1 
	AND A.EXAM_FOR IN ('Eksternal','General')
	AND CONVERT(date, getdate()) BETWEEN CONVERT(date, DATE_EXAM_PERIOD_START) AND CONVERT(date, DATE_EXAM_PERIOD_END)
	--AND DATEADD(DAY, -5, DATE_EXAM_PERIOD_START) <= GETDATE() AND DATEADD(DAY, 5, DATE_EXAM_PERIOD_END) >= GETDATE()