DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@START VARCHAR(50) = @START;
DECLARE @@DISPLAY VARCHAR(50) = @DISPLAY;


SET @@QUERY = '';
SET @@QUERY = 'SELECT 
	*
 FROM 
(
	SELECT ROW_NUMBER() OVER (ORDER BY A.ID_TB_M_USER_MAPPING ASC) ROW_NUM,
	A.ID_TB_M_USER_MAPPING AS ID,
	A.NOREG,
	A.FIRST_NAME,
	A.LAST_NAME,
	A.EMAIL,
	A.USERNAME,
	A.ROLE AS ROLE_ID,
	B.ROLE_NAME AS ROLE,
	A.USER_ST,
	C.AREA_NAME AS AREA,
	A.ID_TB_M_AREA AS AREA_ID,
	D.LOC_NAME AS LOCATION,
	A.ID_TB_M_LOCATION AS LOCATION_ID,
	A.CREATED_BY,
	A.CREATED_DT,
	A.UPDATED_BY,
	A.UPDATED_DT
	FROM TB_M_USER_MAPPING AS A
	INNER JOIN TB_M_ROLE AS B ON A.ROLE = B.ID_TB_M_ROLE
	INNER JOIN TB_M_AREA AS C ON A.ID_TB_M_AREA = C.ID_TB_M_AREA
	INNER JOIN TB_M_LOCATION AS D ON A.ID_TB_M_LOCATION = D.ID_TB_M_LOCATION
	WHERE 1=1
';

IF(@NOREG <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.NOREG LIKE ''%'+@NOREG+'%'' ';
	END

IF(@USERNAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.USERNAME LIKE ''%'+@USERNAME+'%'' ';
	END

IF(@EMAIL <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.EMAIL LIKE ''%'+@EMAIL+'%'' ';
	END

SET @@QUERY = @@QUERY +') as TB';

IF(@@START > 0 AND @@DISPLAY > 0)
BEGIN	
	SET @@QUERY = @@QUERY +' WHERE ROW_NUM BETWEEN '+@@START+' AND '''+@@DISPLAY+''' ';
END

EXEC(@@QUERY)