DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
BEGIN TRY
	UPDATE TB_M_AUTHORIZATION_FUNCTION SET AUTHORIZATION_NAME = @AUTHORIZATION_NAME, AUTHORIZATION_DESC = @AUTHORIZATION_DESC, ID_MENU = @MENUS, ID_MENU_PARENT = @MENU_PARENT, UPDATED_BY = @USERNAME, UPDATED_DT = GETDATE() WHERE ID_TB_M_AUTHORIZATION_FUNCTION = @ID
	SET @@CHK = 'TRUE';
	SET @@ERR = 'Data Has Been Updated';
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR UPDATE TB_M_AUTHORIZATION_FUNCTION:' +@AUTHORIZATION_NAME+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS