DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
BEGIN TRY
	UPDATE TB_M_USER_MAPPING 
		SET 
		NOREG = @NOREG,
		USERNAME = @USERNAME,
		ROLE = @ROLE,
		EMAIL = @EMAIL,
		FIRST_NAME = @FIRST_NAME,
		LAST_NAME = @LAST_NAME,
		ID_TB_M_AREA = @AREA,
		ID_TB_M_LOCATION = @LOCATION,
		UPDATED_BY = @username, 
		UPDATED_DT = GETDATE() 
	WHERE ID_TB_M_USER_MAPPING = @ID
	
	SET @@CHK = 'TRUE';
	SET @@ERR = 'Data Has Been Updated';
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR UPDATE TB_M_USER_MAPPING:' +@NOREG+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS