SELECT  ID,
		WP_PROJECT_ID,
		JOB_NAME,
		WP_IMPB_NO,
		CONVERT(varchar, START_DATE, 23) AS START_DATE,
		CONVERT(varchar, END_DATE, 23) AS END_DATE,
		Job_Status
FROM TB_R_WP_PROJECT_JOB
WHERE WP_PROJECT_ID = @WP_PROJECT_ID;