SELECT M.[ID_TB_M_LEARN_QUESTION] AS [Id]
      ,M.[QUESTION]
      ,M.[ANSWER_CHOICE_A] AS [AnswerChoice_A]
      ,M.[ANSWER_CHOICE_B] AS [AnswerChoice_B]
      ,M.[ANSWER_CHOICE_C] AS [AnswerChoice_C]
      ,M.[ANSWER_CHOICE_D] AS [AnswerChoice_D]
      ,M.[ANSWER_CHOICE_E] AS [AnswerChoice_E]
      ,M.[ANSWER_KEY] AS [AnswerUserChoose]
      ,M.[IMAGE] AS [ImagePath]
  FROM [AB070_DB].[dbo].[TB_M_LEARN_QUESTION] AS M
	LEFT JOIN [AB070_DB].[dbo].[TB_R_LEARN_EXAM_QUESTION] AS R
		ON M.ID_TB_M_LEARN_QUESTION = R.ID_TB_M_LEARN_QUESTION
  WHERE R.ID_TB_R_LEARN_EXAM_SUBJECT = @SUBJECTID AND R.IS_DELETED = 0
  ORDER BY M.[ID_TB_M_LEARN_QUESTION] ASC