IF NOT EXISTS(SELECT 1 FROM TB_R_ALC_DATA_H)
	OR (SELECT COUNT(1) FROM TB_R_ALC_DATA_H A WHERE NOT EXISTS(SELECT 1
															FROM TB_S_HARIGAMI_H B
															WHERE B.LOGICAL_TERMINAL = A.LOGICAL_TERMINAL
																AND B.BC_TYPE = A.BC_TYPE
																AND B.VIN_NO = A.VIN_NO
																AND B.PLANT_CD = A.PLANT_CD
																AND B.SEQ_NO = A.SEQ_NO)) = 0
BEGIN
	SELECT 0
END
ELSE
BEGIN
	SELECT TOP 1 CAST(ISNULL(SEQ_NO, 0) AS NUMERIC)
	FROM TB_R_ALC_DATA_H A
	WHERE NOT EXISTS(SELECT 1
						FROM TB_S_HARIGAMI_H B
						WHERE B.LOGICAL_TERMINAL = A.LOGICAL_TERMINAL
							AND B.BC_TYPE = A.BC_TYPE
							AND B.VIN_NO = A.VIN_NO
							AND B.PLANT_CD = A.PLANT_CD
							AND B.SEQ_NO = A.SEQ_NO)
	ORDER BY SEQ_NO DESC
END