DECLARE @@CHK INT;

SET @@CHK = (SELECT CHARINDEX('@',@USERNAME));

IF(@@CHK > 0)
BEGIN
	SELECT * FROM TB_M_EMPLOYEE WHERE EMAIL = @USERNAME AND PASSWORD = @PASSWORD
END
ELSE
BEGIN
	SELECT * FROM TB_M_EMPLOYEE WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD
END

