DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);

BEGIN TRY
	SET @@CNT = (SELECT COUNT(1) FROM TB_M_ROLE WHERE ROLE_NAME = @ROLE_NAME);
	IF(@@CNT > 0)
	BEGIN
		SET @@CHK = 'FALSE';
		SET @@ERR = 'Data Has been Registered';
		
	END ELSE
	BEGIN
		
		INSERT INTO TB_M_ROLE
		(
			 [ID_TB_M_AUTHORIZATION_FUNCTION]
			,[ROLE_NAME]
			,[ROLE_ST]
			,[ROLE_DESC]
			,[SESSION_TIME_OUT]
			,[LOCK_TIME_OUT]
			,[CREATED_BY]
			,[CREATED_DT]
			,[UPDATED_BY]
			,[UPDATED_DT]
			,[IS_DELETED]
			
		)
		VALUES
		(
			@AUTH,
			@ROLE_NAME,
			@ROLE_STATUS,
			@ROLE_DESC,
			@SESSION_TIME_OUT,
			@LOCK_TIME_OUT,
			@USERNAME,
			GETDATE(),
			@USERNAME,
			GETDATE(),
			0
		);


		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';
	END
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR INSERT TB_M_ROLE:' +@ROLE_NAME+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS