DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
BEGIN TRY
	UPDATE TB_M_LEARN_QUESTION SET 
							QUESTION = @QUESTION
							,CATEGORY = @Category
							,ANSWER_CHOICE_A = @ANSWER_CHOICE_A
							,ANSWER_CHOICE_B = @ANSWER_CHOICE_B
							,ANSWER_CHOICE_C = @ANSWER_CHOICE_C
							,ANSWER_CHOICE_D = @ANSWER_CHOICE_D
							,ANSWER_CHOICE_E = @ANSWER_CHOICE_E
							,ANSWER_KEY = @ANSWER_KEY
							,IMAGE = @IMAGE
							,UPDATED_BY = @USERNAME
							,UPDATED_DT = GETDATE()
					WHERE ID_TB_M_LEARN_QUESTION = @ID
	SET @@CHK = 'TRUE';
	SET @@ERR = 'Data Has Been Updated';
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR UPDATE TB_M_LEARN_QUESTION:' +@QUESTION+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS