DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@START VARCHAR(50) = @START;
DECLARE @@DISPLAY VARCHAR(50) = @DISPLAY;


SET @@QUERY = '';
SET @@QUERY = 'SELECT * FROM ( 
	SELECT 
	   ROW_NUMBER() OVER (ORDER BY A.TRANS_DATE DESC) ROW_NUM,
	   A.ID_TRANS as ID,
       A.ID_TRANS as ID_BUNDLE,
       A.DMC_CODE,
	   A.QTY_STD as QTY_BUNDLE_STD,
	   A.QTY as QTY_BUNDLE_ACT,
	   A.BERAT_BUNDLE_STD as BERAT_BUNDLE_STD,
	   A.BERAT_BUNDLE_ACT as BERAT_BUNDLE_ACT,
	   A.BERAT_PCS_STD as BERAT_PCS_STD,
	   A.AVG_BERAT_PCS,
	   A.JENIS_LOTTO,
	   A.STATUS_LOTTO,
	   A.NIK_GAIKAN,
	   A.OPR_GAIKAN,
	   A.KETERANGAN,
	   A.SHF as SHIFT,
	   A.KALI_PRINT as JML_PRINT,
	   FORMAT(A.TRANS_DATE, ''dd-MM-yyyy hh:mm:ss'') as TRANS_DATE,
	   CASE WHEN A.STATUS_CHECKER IS NULL THEN '''' ELSE ''Sudah Scan'' END AS STATUS_CHECKER,
	   B.NAME_SAGYOSHA AS CHECKER,
	   FORMAT(A.CHECKER_DATE, ''dd-MM-yyyy hh:mm:ss'') as CHECKER_DATE,
	   c.NAME_SAGYOSHA AS INPUT_ADM,
	   FORMAT(A.INPUT_DATE, ''dd-MM-yyyy hh:mm:ss'') as INPUT_DATE,
	   D.NAME_SAGYOSHA AS UPDATE_ADM,
	   FORMAT(A.UPDATE_DATE, ''dd-MM-yyyy hh:mm:ss'') as UPDATE_DATE
    FROM dbo.Z_REX_Data_InOut_FG_New A
		LEFT JOIN Z_RT_master_sagyosha B ON A.checker = B.id_sagyosha
		LEFT JOIN Z_RT_master_sagyosha C ON A.INPUT_ADM = C.id_sagyosha
		LEFT JOIN Z_RT_master_sagyosha D ON A.UPDATE_ADM = D.id_sagyosha
    WHERE 1=1 and id_trans like ''B%''';

IF(@ID_BUNDLE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ID_TRANS LIKE ''%'+@ID_BUNDLE+'%'' ';
	END
IF(@DMC_CODE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND DMC_CODE LIKE ''%'+@DMC_CODE+'%'' ';
	END

IF(@NIK_GAIKAN <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND NIK_GAIKAN LIKE ''%'+@NIK_GAIKAN+'%'' ';
	END
	
IF(@OPR_GAIKAN <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND OPR_GAIKAN LIKE ''%'+@OPR_GAIKAN+'%'' ';
	END

IF(@TRANS_DATE <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND TRANS_DATE >= '''+@TRANS_DATE+' 0:00:00'' ';
	END

IF(@TRANS_DATETO <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND TRANS_DATE <= '''+@TRANS_DATETO+' 23:59:59'' ';
	END

SET @@QUERY = @@QUERY +') as TB';

IF(@@START > 0 AND @@DISPLAY > 0)
BEGIN	
	SET @@QUERY = @@QUERY +' WHERE ROW_NUM BETWEEN '+@@START+' AND '''+@@DISPLAY+''' ';
END

EXEC(@@QUERY)