DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@START VARCHAR(50) = @START;
DECLARE @@DISPLAY VARCHAR(50) = @DISPLAY;


SET @@QUERY = '';
SET @@QUERY = 'SELECT 
	*
 FROM 
(
  	SELECT 
		ROW_NUMBER() OVER (ORDER BY A.ID_TB_M_LEARN_QUESTION ASC) ROW_NUM,
		A.ID_TB_M_LEARN_QUESTION AS ID,
		A.CATEGORY AS CATEGORY_ID,
		B.SYSTEM_VALUE_TXT AS CATEGORY,
		A.QUESTION,
		A.ANSWER_CHOICE_A,
		A.ANSWER_CHOICE_B,
		A.ANSWER_CHOICE_C,
		A.ANSWER_CHOICE_D,
		A.ANSWER_CHOICE_E,
		A.ANSWER_KEY,
		A.IMAGE,
		A.IS_DELETED,
		A.CREATED_BY,
		A.CREATED_DT,
		A.UPDATED_BY,
		A.UPDATED_DT
	FROM 
		TB_M_LEARN_QUESTION A
		LEFT JOIN TB_M_SYSTEM B ON B.SYSTEM_CD = A.CATEGORY
	WHERE 
		A.IS_DELETED = 0
';

IF(@QUESTION <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND QUESTION LIKE ''%'+@QUESTION+'%'' ';
	END

IF(@ANSWER_KEY <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND ANSWER_KEY LIKE ''%'+@ANSWER_KEY+'%'' ';
	END

SET @@QUERY = @@QUERY +') as TB';

IF(@@START > 0 AND @@DISPLAY > 0)
BEGIN	
	SET @@QUERY = @@QUERY +' WHERE ROW_NUM BETWEEN '+@@START+' AND '''+@@DISPLAY+''' ';
END

EXEC(@@QUERY)