SELECT COUNT(NUMBER) 
 FROM (
 	SELECT ROW_NUMBER() OVER (ORDER BY  START_DT DESC) NUMBER
	  ,A.PROCESS_ID      
	  ,A.START_DT
      ,A.END_DT
      ,A.MODULE_ID
      ,A.FUNCTION_ID
      ,A.PROCESS_STATUS
      ,A.USER_ID
      ,A.READ_FLAG
      ,A.REMARK
  FROM TB_R_LOG_H A
  LEFT JOIN TB_M_FUNCTION B
  ON A.FUNCTION_ID = B.FUNCTION_ID AND A.MODULE_ID = b.MODULE_ID
  WHERE
	(CAST(A.START_DT AS DATE) BETWEEN ISNULL(CAST(@ProcessDtFrom AS DATE), CAST(A.START_DT AS DATE)) AND ISNULL(CAST(@ProcessDtTo AS DATE), CAST(A.START_DT AS DATE)))
  AND 
  A.PROCESS_STATUS LIKE '%' + ISNULL(@Status, '%') + '%' 
  AND
  A.PROCESS_ID LIKE '%' + ISNULL(@ProcessID, '%') + '%' 
  AND
  A.FUNCTION_ID LIKE '%' + ISNULL(@FunctionID, '%') + '%' 
  )AS DATA
  