select
	A.ID_TB_R_LEARN_EXAM_SCORE AS ID
	,ROW_NUMBER() OVER (ORDER BY B.REG_NO, (B.FIRST_NAME + ' '+ B.LAST_NAME), C.TITLE) RowNum
	,B.REG_NO
	,(B.FIRST_NAME + ' '+ B.LAST_NAME) AS [NAME]
	,B.IDENTITY_TYPE
	,B.IDENTITY_NO
	,B.USERNAME
	,B.EMAIL
	,C.TITLE
	,A.CORRECT_AMOUNT
	,A.WRONG_AMOUNT
	,A.NOT_ANSWERED_AMOUNT
	,A.REMEDIAL
	,A.SCORE
	,A.PASS_GRADUATED
	,A.TIMER
	,A.SUBMIT_DATE
	,A.IS_STATUS
from 
	TB_R_LEARN_EXAM_SCORE A
	LEFT JOIN TB_M_EMPLOYEE B ON A.ID_TB_M_EMPLOYEE = B.ID_TB_M_EMPLOYEE
	LEFT JOIN TB_R_LEARN_EXAM_SUBJECT C ON A.ID_TB_R_LEARN_EXAM_SUBJECT = C.ID_TB_R_LEARN_EXAM_SUBJECT
where
	B.REG_NO like '%' + @RegNo + '%'
	AND B.IDENTITY_TYPE like '%'+ @IdentityType +'%' 
	AND B.IDENTITY_NO like '%'+ @IdentityNo +'%' 
	AND B.USERNAME like '%'+ @UserName +'%' 
	AND B.EMAIL like '%'+ @Email +'%'
order by
	B.REG_NO, (B.FIRST_NAME + ' '+ B.LAST_NAME)




