DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@DATA_ID VARCHAR(MAX) = @DATA_ID;
DECLARE @@TIME_UNIT_CRITERIA VARCHAR(MAX) = @TIME_UNIT_CRITERIA;
DECLARE @@EXECUTION_TIME VARCHAR(MAX) = @EXECUTION_TIME;
DECLARE @@STATUS_ACTIVE VARCHAR(MAX) = @STATUS_ACTIVE;

SET @@QUERY = '';
SET @@QUERY = '
	SELECT ISNULL(max(ROW_NUM),0) FROM 
	(
		SELECT ROW_NUMBER() OVER (ORDER BY A.ID_TB_M_ITEM ASC) ROW_NUM,
		A.ID_TB_M_ITEM,
		A.ITEM_NAME,
		A.ITEM_ST,
		A.ITEM_TYPE,
		(SELECT SYSTEM_VALUE_TXT FROM TB_M_SYSTEM WHERE SYSTEM_ID = ''WP_ITEM_TYPE'' AND SYSTEM_CD = A.ITEM_TYPE) AS ITEM_TYPE_VAL,
		A.ITEM_DESC,
		A.CREATED_BY,
		A.CREATED_DT,
		A.UPDATED_BY,
		A.UPDATED_DT
		FROM TB_M_ITEM AS A
		WHERE 1=1 AND IS_DELETED = 0
';

IF(@ITEM_NAME <> '')
	BEGIN
		SET @@QUERY = @@QUERY + 'AND A.ITEM_NAME LIKE ''%'+RTRIM(@ITEM_NAME)+'%'' ';
	END

SET @@QUERY = @@QUERY +') as TB';


EXEC(@@QUERY);

