DECLARE @@QUERY VARCHAR(MAX);
DECLARE @@DATA_ID VARCHAR(MAX) = @DATA_ID;
DECLARE @@TIME_UNIT_CRITERIA VARCHAR(MAX) = @TIME_UNIT_CRITERIA;
DECLARE @@EXECUTION_TIME VARCHAR(MAX) = @EXECUTION_TIME;
DECLARE @@STATUS_ACTIVE VARCHAR(MAX) = @STATUS_ACTIVE;

SET @@QUERY = '';
SET @@QUERY = '
	SELECT ISNULL(max(ROW_NUM),0) FROM 
	(
		SELECT ROW_NUMBER() OVER (ORDER BY a.ID ASC) ROW_NUM, ID,
	Project_CD, Location, Pekerjaan AS JOBS, HighLevel, MediumLevel, LowLevel, convert(varchar(10),Tanggal_Pekerjaan) AS DATE, remarks, CREATE_BY, CREATE_DT, UPDATE_BY, UPDATE_DT, Category
	FROM dbo.TB_R_WP_DETAIL as a 
	) AS TB';

EXEC(@@QUERY);

