DECLARE @@CNT INT
	, @@CHK VARCHAR(20)
	, @@ERR VARCHAR(MAX);
DECLARE @@MSG_TEXT VARCHAR(MAX);
DECLARE @@MSG_TYPE VARCHAR(MAX);

BEGIN TRY
	SET @@CNT = (SELECT COUNT(1) FROM TB_R_WP_DETAIL_IMPLEMENTOR WHERE ID = @ID);
	IF(@@CNT > 0)
	BEGIN
		UPDATE TB_R_WP_DETAIL_IMPLEMENTOR
		SET EXECUTOR = @EXECUTOR ,
			ID_TB_M_COMPANY = @ID_TB_M_COMPANY,
			EMPLOYEE_LEAD_PROJECT = @EMPLOYEE_LEAD_PROJECT,
			EMPLOYEE_SUPERVISOR_PROJECT = @EMPLOYEE_SUPERVISOR_PROJECT
		WHERE ID = @ID

		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';		
	END ELSE
	BEGIN
		INSERT INTO TB_R_WP_DETAIL_IMPLEMENTOR
		(
			WP_PROJECT_JOB_ID ,
			EXECUTOR ,
			ID_TB_M_COMPANY ,
			EMPLOYEE_LEAD_PROJECT ,
			EMPLOYEE_SUPERVISOR_PROJECT,
			[CREATED_BY],
			[CREATED_DT],
			[CHANGED_BY],
			[CHANGED_DT]
			
		)
		VALUES
		(
			@WP_PROJECT_JOB_ID ,
			@EXECUTOR ,
			@ID_TB_M_COMPANY ,
			@EMPLOYEE_LEAD_PROJECT ,
			@EMPLOYEE_SUPERVISOR_PROJECT,
			@USERNAME,
			GETDATE(),
			@USERNAME,
			GETDATE()
		);


		SET @@CHK = 'TRUE';
		SET @@ERR = 'NOTHING';
	END
END TRY
BEGIN CATCH
	SET @@CHK = 'FALSE';
	SET @@ERR = 'ERROR INSERT DETAIL_IMPLEMENTOR:' +@WP_IMPB_NO+
	'<br/>Detail Error :|: ' + ERROR_MESSAGE() + ' :|: ';	
END CATCH

SELECT @@CHK AS STACK, @@ERR AS LINE_STS