//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI070.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    public partial class ad_dis_rtjn_master_actual_masalah
    {
        public string ID { get; set; }
        public string DATE { get; set; }
        public string TIME { get; set; }
        public string HALTE { get; set; }
        public string OPMJ { get; set; }
        public string MASALAH { get; set; }
        public string ACTION { get; set; }

    }
}
