SELECT 
	SYSTEM_ID
    ,SYSTEM_TYPE
    ,SYSTEM_CD AS ID
    ,SYSTEM_VALUE_TXT AS CATEGORY
	,SYSTEM_VALID_FR
    ,SYSTEM_VALID_TO
FROM 
	TB_M_SYSTEM
where 
	SYSTEM_ID = 'WP_QUESTION_BANK_CATEGORY'
	AND IS_DELETED = 0


